### ISSUE TITLE
Error in logs when trying custom component through HACS

### ISSUE THREAD

**Issue by freshfieldx** [alandtse/tesla#1]
Operating System
Home Assistant OS 5.13

Core
Version
core-2021.4.6
Newest Version
core-2021.5.0b1

Supervisor
Version
supervisor-2021.04.3
Newest Version
supervisor-2021.04.3

Logger: custom_components.tesla
Source: custom_components/tesla/__init__.py:253
Integration: Tesla (documentation, issues)
First occurred: 7:58:48 (33 occurrences)
Last logged: 8:30:48

Unexpected error fetching tesla data: 'str' object is not callable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tesla/__init__.py", line 253, in _async_update_data
    return await self.controller.update()
  File "/usr/local/lib/python3.8/site-packages/teslajsonpy/controller.py", line 719, in update
    cars = await self.get_vehicles()
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/teslajsonpy/controller.py", line 407, in get_vehicles
    return (await self.__connection.get("vehicles"))["response"]
  File "/usr/local/lib/python3.8/site-packages/teslajsonpy/connection.py", line 90, in get
    return await self.post(command, "get", None)
  File "/usr/local/lib/python3.8/site-packages/teslajsonpy/connection.py", line 112, in post
    self.code = await self.get_authorization_code(
  File "/usr/local/lib/python3.8/site-packages/teslajsonpy/connection.py", line 405, in get_authorization_code
    html = await resp.text()
TypeError: 'str' object is not callable

**Comment by freshfieldx** [comment]
I had to delete and reinstall and it works, apologies!

**Comment by alandtse** [comment]
Yes, I should've said that. You have to use the new login system for it to work.

**Comment by freshfieldx** [comment]
Thanks for all the work you have put in on this issue, I really appreciate it. Enjoy the Coffee!

**Comment by freshfieldx** [comment]
All my Tesla dashboards have burst into life again...much easier to transition from core to custom than I was expecting!
