### ISSUE TITLE
Two cars on one fleet API?

### ISSUE THREAD

**Issue by Chacsam** [alandtse/tesla#1007]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

3.24.0

### Version of the Tesla car software

2024.8.300

### Model

Model Y

### Current Behavior

A second car installed on my fleet API is detected, display sensors, but doesn't accept commands.

### Expected Behavior

commands to respond, any way to do it?

### Debug logs

```true
2024-06-19 06:22:55.662 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:31:31
2024-06-19 06:22:55.662 DEBUG (MainThread) [teslajsonpy.connection] post: https://proxy.home:4430/api/1/vehicles/XPxxxxx8/command/charge_stop {}
2024-06-19 06:22:56.223 DEBUG (MainThread) [teslajsonpy.connection] 500: {"response":null,"error":"vehicle rejected request: your public key has not been paired with the vehicle","error_description":""}

2024-06-19 06:23:00.027 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:31:26
2024-06-19 06:23:00.028 DEBUG (MainThread) [teslajsonpy.connection] post: https://proxy.home:4430/api/1/vehicles/XPxxxxxxxx8/command/charge_stop {}
2024-06-19 06:23:00.470 DEBUG (MainThread) [teslajsonpy.connection] 500: {"response":null,"error":"vehicle rejected request: your public key has not been paired with the vehicle","error_description":""}

2024-06-19 06:23:00.470 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140249009879888] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tesla_custom/switch.py", line 119, in async_turn_off
    await self._car.stop_charge()
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 1180, in stop_charge
    data = await self._send_command("STOP_CHARGE", wake_if_asleep=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 785, in _send_command
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 770, in _send_command
    data = await self._controller.api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1375, in api
    return await self.__post_with_retries_except_unavailable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 142, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 58, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 110, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 78, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 61, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1407, in __post_with_retries_except_unavailable
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 218, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
2024-06-19 06:23:00.595 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-06-19 06:23:00.595 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 60 Interval 60
2024-06-19 06:23:00.596 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:31:26
2024-06-19 06:23:00.596 DEBUG (MainThread) [teslajsonpy.connection] get: https://proxy.home:4430/api/1/products {}
2024-06-19 06:23:00.708 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-06-19 06:23:00.735 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":[{"id":92xxx51,"user_id":17xxx4,"vehicle_id":16xxx2,"vin":"LRW3Exxx","color":null,"access_type":"OWNER","display_name":"Mxxxxd","option_codes":null,"cached_data":"EicKAgoAEgISAxxxxxx4PgE=","granular_access":{"hide_private":false},"tokens":["187fd9b41892453b","26a9b65947807d48"],"state":"online","in_service":false,"id_s":"929776234487351","calendar_enabled":true,"api_version":76,"backseat_token":null,"backseat_token_updated_at":null,"ble_autopair_enrolled":false,"command_signing":"required","release_notes_supported":true},{"id":9298xxx8445321,"user_id":1xxx74,"vehicle_id":16893xxx00,"vin":"XPxxxx088","color":null,"access_type":"OWNER","display_name":"Yolande","option_codes":null,"cached_data":"Eixxxxx9AG4PgE=","granular_access":{"hide_private":false},"tokens":["xx","xx"],"state":"online","in_service":false,"id_s":"929823868445321","calendar_enabled":true,"api_version":75,"backseat_token":null,"backseat_token_updated_at":null,"ble_autopair_enrolled":false,"command_signing":"required","release_notes_supported":true},{"energy_site_id":x,"resource_type":"wall_connector","id":"x-00218","asset_site_id":"ddb978b2-de33-44e7-x-x","warp_site_number":"x-00218","go_off_grid_test_banner_enabled":null,"storm_mode_enabled":null,"powerwall_onboarding_settings_set":null,"powerwall_tesla_electric_interested_in":null,"vpp_tour_enabled":null,"sync_grid_alert_enabled":false,"breaker_alert_enabled":false,"components":{"battery":false,"solar":false,"grid":false,"load_meter":false,"market_type":"residential","wall_connectors":[{"device_id":"xxx-49a4-92f4-7ebd4a4af68b","din":"xx-02-D--xx","part_number":"xx-02-D","is_active":true}]},"features":{}}],"count":3}
2024-06-19 06:23:00.736 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.141 seconds (success: True)
2024-06-19 06:23:00.736 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 0 Interval 60
2024-06-19 06:23:00.736 DEBUG (MainThread) [teslajsonpy.controller] 66277: online. Polling policy: normal. Update state: normal. Since last park: 10. Since last wake up: 60. Idle interval: 600. shift_state: P sentry: False climate: False, charging: Disconnected 
2024-06-19 06:23:00.736 DEBUG (MainThread) [teslajsonpy.controller] 66277: Resetting last_parked_timestamp to: 1718770981 shift_state P
2024-06-19 06:23:00.736 DEBUG (MainThread) [teslajsonpy.controller] 66277: Skipping update with state online. Polling: True. Last update: 60 ago. Last parked: 0 ago. Last wake up 60 ago. 
2024-06-19 06:23:00.736 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.028 seconds (success: True)
2024-06-19 06:23:00.805 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-06-19 06:23:00.806 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 0 Interval 60
2024-06-19 06:23:00.806 DEBUG (MainThread) [teslajsonpy.controller] 46088: online. Polling policy: normal. Update state: normal. Since last park: 30275.40199995041. Since last wake up: 300. Idle interval: 600. shift_state: None sentry: False climate: False, charging: Charging 
2024-06-19 06:23:00.806 DEBUG (MainThread) [teslajsonpy.controller] 46088: Skipping update with state online. Polling: True. Last update: 300 ago. Last parked: 30275.40199995041 ago. Last wake up 300 ago. 
2024-06-19 06:23:00.807 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.001 seconds (success: True)
```

### Anything else?

I guess the issue is here:
`{"response":null,"error":"vehicle rejected request: your public key has not been paired with the vehicle","error_description":""}`
Do I need 2 different api's? Or 2 different proxies?

**Comment by dandelionclock** [comment]
Did you enroll public key on your new car?

> Using the Home Assistant iOS app, open the Addon Web UI and click Enroll public key in your vehicle. This should launch the Tesla app where it prompts for approval to "allow third-party access to your vehicle". If you have multiple vehicles, you'll need to do this on each of them. Your Tesla app must already be key-paired with the car.


[Home Assistant Add-on: Tesla HTTP Proxy](https://github.com/llamafilm/tesla-http-proxy-addon/blob/main/tesla_http_proxy/DOCS.md)

**Comment by Chacsam** [comment]
That was it, I didn't find it immedialtely as I am on a docker instance, but your response lead me to the solution.
Thanks!
