### ISSUE TITLE
"Vent" no longer working

### ISSUE THREAD

**Issue by MarkRS-UK** [alandtse/tesla#1032]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

v3.24.0

### Version of the Tesla car software

2024.26.6

### Model

Model 3

### Current Behavior

The "Windows" button, ie

![teslaVent](https://github.com/user-attachments/assets/10a7b9aa-c522-40b1-a933-d2bc6f1a374c)

no longer vents the car (ie open all four windows slightly).  The call **does** communicate with the car (I hear the "click") but no action occurs.  Nor does the display reflect the current status (unsurprisingly, I suppose).
This worked until recently, though I'm not sure when it stopped.
Venting using the app *does* work (here).

### Expected Behavior

Pressing this button should cause all four windows to open slightly.

### Debug logs

```true
No log is produced when this action is attempted.
```

**Comment by nivek1385** [comment]
Unsure if mine was working before, but it is not working currently. 
Tesla Integration version 3.24.0
Tesla Car Software Version 2024-20.9
Model Y

**Comment by karaminder** [comment]
ditto with me.

Tesla Integration version 3.24.1
Tesla Car Software Version 2024.32.6 4db1ecca937e
Model S

**Comment by skipishere** [comment]
Does any other command work?
Are you using the fleet API?

Would help if log files were attached

**Comment by KevinBonnoron** [comment]
I have the same issue but I got some errors.
Tesla Integration version 3.24.3
Tesla Car Software Version 2025.14.1 225c2b24b944
Model 3

I can't do any action (open, close car or windows).
Here is the error log i got from home assistant:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2794, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/core.py", line 2837, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/homeassistant/components/lock/__init__.py", line 234, in async_handle_unlock_service
    await self.async_unlock(**self.add_default_code(kwargs))
  File "/config/custom_components/tesla_custom/lock.py", line 43, in async_unlock
    await self._car.unlock()
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/car.py", line 1235, in unlock
    data = await self._send_command("UNLOCK")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/car.py", line 785, in _send_command
    raise ex
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/car.py", line 770, in _send_command
    data = await self._controller.api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        name, path_vars=path_vars, wake_if_asleep=wake_if_asleep, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/controller.py", line 1373, in api
    response = await self.__post_with_retries(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        "", method=method, data=kwargs, url=uri
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.13/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/controller.py", line 1396, in __post_with_retries
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/connection.py", line 223, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
```

**Comment by skipishere** [comment]
@KevinBonnoron are you issuing the fleet API? If not today is probably your issue
