### ISSUE TITLE
Tesla integration "Not loaded"

### ISSUE THREAD

**Issue by boxer747** [alandtse/tesla#1044]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

3.24.1

### Version of the Tesla car software

2024.32.3

### Model

Model Y

### Current Behavior

Integration was working correctly until recent updates. Not sure which update broke it. Now the integration just reads "Not loaded". I have restarted, rebooted and hard reinitialize the host machine. Nothing worked.

### Expected Behavior

I expected the integratio to load and show values.

### Debug logs

```true
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 12:04:37 PM (3 occurrences)
Last logged: 12:04:40 PM

Unable to install package teslajsonpy==3.12.0: ERROR: Exception: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper status = run_func(*args) ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper return func(self, options, args) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 324, in run session = self.get_default_session(options) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/index_command.py", line 71, in get_default_session self._session = self.enter_context(self._build_session(options)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/cli/index_command.py", line 100, in _build_session session = PipSession( ^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/network/session.py", line 344, in __init__ self.headers["User-Agent"] = user_agent() ^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/network/session.py", line 177, in user_agent setuptools_dist = get_default_environment().get_distribution("setuptools") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 189, in get_distribution return next(matches, None) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 184, in <genexpr> matches = ( ^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/base.py", line 612, in iter_all_distributions for dist in self._iter_distributions(): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 176, in _iter_distributions yield from finder.find(location) File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 79, in find for dist, info_location in self._find_impl(location): File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_envs.py", line 64, in _find_impl raw_name = get_dist_name(dist) ^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_compat.py", line 52, in get_dist_name name = cast(Any, dist).name ^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 457, in name return self.metadata['Name'] ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 444, in metadata self.read_text('METADATA') File "/usr/local/lib/python3.12/importlib/metadata/__init__.py", line 819, in read_text return self._path.joinpath(filename).read_text(encoding='utf-8') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/pathlib.py", line 1028, in read_text return f.read() ^^^^^^^^ File "<frozen codecs>", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 8192: invalid start byte
```

**Comment by skipishere** [comment]
I'd uninstall and then try reinstalling and see if that fixes it.

**Comment by cydrezz** [comment]
for me re-authentication successful but fails to setup #895 that helped

**Comment by skipishere** [comment]
> for me re-authentication successful but fails to setup #895 that helped reinstall did not work

Are you getting the same log entry? If not then you are having a different problem

**Comment by cydrezz** [comment]
I still have a bit of trouble understanding logs so i did not copy it sorry what i did see are these 2 errors:
Config flow could not be loaded: {"message":"Invalid flow specified"}
Failed to set up: could not authenticate

**Comment by skipishere** [comment]
Ok so not related to this issue then, please keep related things together or create a new issue.

**Comment by jbouter** [comment]
I've got the exact same issue, today's update sadly didn't  fix it either.

Startup logs:

```
 Unable to install package teslajsonpy==3.12.3: error: failed to remove file `/usr/local/lib/python3.12/site-packages/../../../bin/typer` Caused by: Permission denied (os error 13) 
```

I am using the [HomeAssistant container from linuxserver.io](https://docs.linuxserver.io/images/docker-homeassistant/)

**Comment by jbouter** [comment]
I've resolved my issue by adding the [Package install universal docker mod](https://github.com/linuxserver/docker-mods/tree/universal-package-install) specifically for containers by `linuxserver.io`. I'm using it to install `teslajsonpy`, because apparently linuxserver.io containers now use `uv` instead of `pip` and the tesla addon through HACS cannot install the required package.
