### ISSUE TITLE
'Teslamate ID' isn't retained

### ISSUE THREAD

**Issue by Nick-Sills** [alandtse/tesla#1055]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

v3.24.1

### Version of the Tesla car software

2024.32.9

### Model

Model S

### Current Behavior

I'm using Teslamate MQT for the Tesla custom integration.  Everything works for a few minutes then the  `Teslamate ID` reverts from `1`  to `unknown`, and MQTT stops syncing.

### Expected Behavior

`Teslamate ID` to be persistent

### Debug logs

```true
Log when working:
2024-10-19 09:53:27.894 INFO (MainThread) [custom_components.tesla_custom.teslamate] Created mqtt Topic for: teslamate/cars/1/#
2024-10-19 09:53:27.894 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Subscribed to MQTT Topics
2024-10-19 09:53:27.894 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Completed watch_cars
2024-10-19 09:53:28.077 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] MQTT Topic Recieved: teslamate/cars/1/latitude
2024-10-19 09:53:28.077 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Getting TeslaCar for teslaMateID:1
2024-10-19 09:53:28.077 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Got latitude from MQTT for VIN:5YJSB7E43GF158755 | TeslsMateID:1
2024-10-19 09:53:28.077 DEBUG (MainThread) [custom_components.tesla_custom.teslamate] Updating state 'latitude' to value '53.443722' in sub_path 'drive_state' for VIN:5YJSB7E43GF158755
etc..

There are no MQTT logs in the log after 'Teslamate ID' reverts to 'unknown'
```

**Comment by Nick-Sills** [comment]
@alandtse `Teslamate ID` changed from unknown back to 1 after several hours, and now appears to be stable:

![image](https://github.com/user-attachments/assets/1e27a833-f531-4a1a-9e6d-6b677c7014bd)

So now things appear to be working correctly. 

I noticed these errors in the log, and I'm not sure if it was the cause of the original problem, or whether the  should/can be fixed.

```
024-10-20 16:42:06.847 ERROR (SyncWorker_46) [homeassistant.util.logging] Exception in msg_recieved when handling msg on 'teslamate/cars/1/charger_actual_current': ''
Traceback (most recent call last):
  File "/config/custom_components/tesla_custom/teslamate.py", line 310, in msg_recieved
    ).result()
      ^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/config/custom_components/tesla_custom/teslamate.py", line 359, in async_handle_new_data
    self.update_car_state(car, "charge_state", attr, cast(msg.payload))
                                                     ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

2024-10-20 16:42:06.851 ERROR (SyncWorker_12) [homeassistant.util.logging] Exception in msg_recieved when handling msg on 'teslamate/cars/1/charger_voltage': ''
Traceback (most recent call last):
  File "/config/custom_components/tesla_custom/teslamate.py", line 310, in msg_recieved
    ).result()
      ^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/config/custom_components/tesla_custom/teslamate.py", line 359, in async_handle_new_data
    self.update_car_state(car, "charge_state", attr, cast(msg.payload))
                                                     ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

2024-10-20 16:42:06.855 ERROR (SyncWorker_60) [homeassistant.util.logging] Exception in msg_recieved when handling msg on 'teslamate/cars/1/charger_power': ''
Traceback (most recent call last):
  File "/config/custom_components/tesla_custom/teslamate.py", line 310, in msg_recieved
    ).result()
      ^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
```


As things appear to be working now so this issue can be closed, unless fixing those errors is relevant.

**Comment by Stono** [comment]
I also have this issue!  No error logs in anything however.  Cannot get it to save the id, it's just `unknown`.

**Comment by Stono** [comment]
OK restarting the teslamate addon and it's now `1`

**Comment by segdy** [comment]
Awesome, thank you very much! Had the same issue and this fixed it.
However, how can I confirm that it works?

As per documentation I enabled debug logging but System -> Logs stays empty. I can confirm updated MQTT messages with MQTTExplorer...
