### ISSUE TITLE
devices become unavailable every 2-3 minutes

### ISSUE THREAD

**Issue by elijah286** [alandtse/tesla#1077]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

3.24.3

### Version of the Tesla car software

2024.12.4

### Model

Model S, Model X

### Current Behavior

All devices on the vehicles become unavailable every few minutes. They come back after about 30 seconds, only to become unavailable again a few minutes later. Note that this is only happening to the vehicles - it is not happening to the energy products

### Expected Behavior

It should maintain a stead connection, but periodically becomes unavailable

### Debug logs

```true
This error originated from a custom integration.

Logger: custom_components.tesla_custom
Source: helpers/update_coordinator.py:385
integration: Tesla Custom Integration (documentation, issues)
First occurred: 2:41:32 PM (311 occurrences)
Last logged: 5:02:42 PM

Timeout fetching tesla_custom data
```

### Anything else?

It's been working reliably for months and I haven't changed the configuration

**Comment by elijah286** [comment]
Another clue I found in the log:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 5:06:13 PM (1 occurrences)
Last logged: 5:06:13 PM

Detected that custom integration 'tesla_custom' sets option flow config_entry explicitly, which is deprecated at custom_components/tesla_custom/config_flow.py, line 204: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/alandtse/tesla/issues

**Comment by elijah286** [comment]
And another clue.. sorry for posting three different log files but I'm just hoping something in here is useful:

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/tesla_custom/sensor.py:445
integration: Tesla Custom Integration (documentation, issues)
First occurred: 2:14:04 PM (1016 occurrences)
Last logged: 5:16:12 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 267, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 558, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 557, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/sensor.py", line 445, in native_value
    return round(self._energysite.energy_left)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/teslajsonpy/energy.py", line 152, in energy_left
    return round (self._site_config.get("nameplate_energy") * self.percentage_charged / 100 )
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'
`

**Comment by Pranav1904** [comment]
Hi @elijah286, this is my first time contributing to open source. Is this issue still open? I’d love to help out and work on it!
