### ISSUE TITLE
"Home Energy Gateway Off-grid operation" returns "User does not have adequate access rights"

### ISSUE THREAD

**Issue by bardolan** [alandtse/tesla#1078]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

v3.19.3

### Version of the Powerwall Gateway software

24.44.0 510adfd5

### Model

Powerwall Backup Gateway 2

### Current Behavior

The entity "Home Energy Gateway Off-grid operation", which normally functions as a switch for the off-gird operation mode has failed multiple times today with the message "Failed to perform the action switch/turn_on. Setting off-grid operation to IslandMode.OFFGRID failed: Access denied for resource https://IP-REDACTED/api/v2/islanding/mode: Unable to POST to resource: User does not have adequate access rights"

The issue was first noticed this morning 12/23/24, though it could have begun anytime after 10:10PM EST 12/21/24 as the associated automation does not run over weekends and therefore i only noticed the issue thios morning.

HA Core 2024.12.5
Supervisor 2024.12.0
OS 14.1
Frontend 20241127.8

### Expected Behavior

The expected behavior is for the "Home Energy Gateway Off-grid operation" switch to change the state of the off-grid operation for the home energy gateway.

### Debug logs

```true
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 5:37:52 PM (6 occurrences)
Last logged: 5:58:21 PM

[547041072400] Unexpected exception
[546967726560] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/powerwall/switch.py", line 59, in _async_set_island_mode
    await self.power_wall.set_island_mode(island_mode)
  File "/usr/local/lib/python3.13/site-packages/tesla_powerwall/powerwall.py", line 185, in set_island_mode
    await self._api.post_islanding_mode({"island_mode": mode.value}),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tesla_powerwall/api.py", line 262, in post_islanding_mode
    return await self.post("v2/islanding/mode", body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tesla_powerwall/api.py", line 134, in post
    return await self._process_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/tesla_powerwall/api.py", line 78, in _process_response
    await self._handle_error(response)
  File "/usr/local/lib/python3.13/site-packages/tesla_powerwall/api.py", line 53, in _handle_error
    raise AccessDeniedError(
    ...<3 lines>...
    )
tesla_powerwall.error.AccessDeniedError: Access denied for resource https://192.168.10.5/api/v2/islanding/mode: Unable to POST to resource: User does not have adequate access rights

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/powerwall/switch.py", line 50, in async_turn_on
    await self._async_set_island_mode(IslandMode.OFFGRID)
  File "/usr/src/homeassistant/homeassistant/components/powerwall/switch.py", line 61, in _async_set_island_mode
    raise HomeAssistantError(
        f"Setting off-grid operation to {island_mode} failed: {ex}"
    ) from ex
homeassistant.exceptions.HomeAssistantError: Setting off-grid operation to IslandMode.OFFGRID failed: Access denied for resource https://192.168.10.5/api/v2/islanding/mode: Unable to POST to resource: User does not have adequate access rights
```

### Anything else?

You are amazing. If you find yourself in West Florida I will gladly cook you dinner.

**Comment by alandtse** [comment]
This is not the correct integration. We are not the power wall integration.

**Comment by bardolan** [comment]
Well crud, your integration was hands down the best for interfacing with the powerwall/home energy gateway via the "Include Energy Sites" checkbox that pops up as part of the intial configuration, and exposed several entities (most of which still function).
Ah well, thank you for what you had done while it lasted, even if it was unintentional.

**Comment by alandtse** [comment]
My point is you're using the [official power wall integration](https://www.home-assistant.io/integrations/powerwall/) and not this custom component. See the logs `homeassistant/components/powerwall`.  Reporting here won't change anything as it isn't the code from here but from the official component.
