### ISSUE TITLE
httpx.CookieConflict: Multiple cookies exist with name=_abck

### ISSUE THREAD

**Issue by s450586793** [alandtse/tesla#11]
此错误来自自定义集成。

Logger: aiohttp.server
Source: custom_components/tesla_custom/config_flow.py:132
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 22:57:35 (3 occurrences)
Last logged: 22:57:38

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 146, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 95, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tesla_custom/config_flow.py", line 132, in async_step_finish_oauth
    self.controller.set_authorization_code(self.data.get("code", ""))
AttributeError: 'NoneType' object has no attribute 'get'

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by s450586793** [comment]
![image](https://user-images.githubusercontent.com/53229926/128728156-cf5837b8-75e6-4eac-858e-4ba1c6e1ac14.png)

**Comment by alandtse** [comment]
Does the component allow you to access the login page at all? Please provide debug logs for `authcaptureproxy`.

**Comment by s450586793** [comment]
The following is from Google Translate
I installed alandtse/tesla
After clicking Configure on the integration page, jump to Tesla sso -sign in, enter the account password, jump to 500 Internal Server Error Server got itself in trouble
I am a Tesla China account

**Comment by s450586793** [comment]
2021-08-10 09:40:57 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tesla_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-10 09:40:57 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pr_custom_component which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-10 09:40:57 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration climate_ewelink which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-10 09:40:57 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-10 09:40:57 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_miot_raw which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-10 09:41:09 ERROR (MainThread) [custom_components.hacs] DavidFW1960/bom_forecast - Repository is archived.
2021-08-10 09:41:09 ERROR (MainThread) [custom_components.hacs] bieniu/ha-gios - Repository is archived.
2021-08-10 09:41:09 ERROR (MainThread) [custom_components.hacs] avdeevsv91/ha_generic_hygrostat - Repository is archived.
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck
2021-08-10 09:44:12 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
return await cls.handler(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 362, in all_handler
for cookie, value in self.session.cookies.items():
File "/usr/local/lib/python3.9/_collections_abc.py", line 850, in __iter__
yield (key, self._mapping[key])
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1780, in __getitem__
value = self.get(name)
File "/usr/local/lib/python3.9/site-packages/httpx/_models.py", line 1733, in get
raise CookieConflict(message)
httpx.CookieConflict: Multiple cookies exist with name=_abck

**Comment by alandtse** [comment]
There is a simple fix if you feel comfortable modifying the authcaptureproxy library.

In the /usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py file you can delete lines 361-370:

This is before:
```python
            if skip_auto_headers:
                _LOGGER.debug("Discovered skip_auto_headers %s", skip_auto_headers)
                headers.pop(SKIP_AUTO_HEADERS)
            cookies = {}
            for cookie, value in self.session.cookies.items():
                cookies[cookie] = value
            _LOGGER.debug(
                "Attempting %s to %s\nheaders: %s \ncookies: %s",
                method,
                site,
                headers,
                cookies,
            )
            try:
                if mpwriter:
                    resp = await getattr(self.session, method)(site, data=mpwriter, headers=headers)
```

This is after:
```python
            if skip_auto_headers:
                _LOGGER.debug("Discovered skip_auto_headers %s", skip_auto_headers)
                headers.pop(SKIP_AUTO_HEADERS)
            try:
                if mpwriter:
                    resp = await getattr(self.session, method)(site, data=mpwriter, headers=headers)
```

I will have an official fix but I do not know when I'll release it.

**Comment by alandtse** [comment]
https://github.com/alandtse/tesla/issues/12#issuecomment-896466746 shows how to install in your config.
