### ISSUE TITLE
 CHARGING_AMPS and CHANGE_CHARGE_LIMIT error

### ISSUE THREAD

**Issue by fernandeusto** [alandtse/tesla#143]
## Describe the bug

CHARGING_AMPS and CHANGE_CHARGE_LIMIT error

Logger: homeassistant.components.automation.wallbox_limite_carga
Source: custom_components/tesla_custom/services.py:110
Integration: Automatización (documentation, issues)
First occurred: 01:47:07 (2 occurrences)
Last logged: 01:47:07

Wallbox Limite Carga Slider: Error executing script. Unexpected error for call_service at pos 1:
While executing automation automation.wallbox_limite_carga
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 584, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 54, in async_call_tesla_service
    await api(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 110, in api
    return await controller.api(name=command, path_vars=path_vars, **parameters)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 170, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 1726, in api
    return await self.__connection.post(
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 168, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 217, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tesla_custom/services.py:110
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 01:33:43 (3 occurrences)
Last logged: 01:34:05

[140539277649520]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 54, in async_call_tesla_service
    await api(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 110, in api
    return await controller.api(name=command, path_vars=path_vars, **parameters)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 170, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 1726, in api
    return await self.__connection.post(
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 168, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 217, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException

**Comment by fernandeusto** [comment]
sorry, i was send other car id. it change recently.

now run ok
