### ISSUE TITLE
KeyError: 'access_token'

### ISSUE THREAD

**Issue by kennedyshead** [alandtse/tesla#174]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiohttp-3.8.1-py3.9-linux-x86_64.egg/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp-3.8.1-py3.9-linux-x86_64.egg/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp-3.8.1-py3.9-linux-x86_64.egg/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 164, in post
    return await super().post(request, flow_id)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/home/knutas/.local/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/home/knutas/.hass/custom_components/tesla_custom/config_flow.py", line 63, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/home/knutas/.hass/custom_components/tesla_custom/config_flow.py", line 182, in validate_input
    result = await controller.connect(test_login=True)
  File "/home/knutas/.hass/deps/lib/python3.9/site-packages/teslajsonpy/controller.py", line 393, in connect
    cars = await self.get_vehicles()
  File "/home/knutas/.hass/deps/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/home/knutas/.hass/deps/lib/python3.9/site-packages/teslajsonpy/controller.py", line 523, in get_vehicles
    return (await self.api("VEHICLE_LIST"))["response"]
  File "/home/knutas/.hass/deps/lib/python3.9/site-packages/teslajsonpy/controller.py", line 171, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/home/knutas/.hass/deps/lib/python3.9/site-packages/teslajsonpy/controller.py", line 1754, in api
    return await self.__connection.post("", method="get", data=kwargs, url=uri)
  File "/home/knutas/.hass/deps/lib/python3.9/site-packages/teslajsonpy/connection.py", line 162, in post
    access_token=auth["access_token"], expires_in=auth["expires_in"]
KeyError: 'access_token'

**Comment by kennedyshead** [comment]
auth contains: `{'error': 'unsupported_grant_type', 'error_description': 'The authorization grant type is not supported by the authorization server.'}`

**Comment by alandtse** [comment]
Update to the latest.

**Comment by kennedyshead** [comment]
I'm on 1.7.0 is there a later version?

Den lör 26 mars 2022 18:22Alan Tse ***@***.***> skrev:

**Comment by alandtse** [comment]
That code doesn't exist in 1.7.0. https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/connection.py#L162

Ensure you don't have a custom copy of teslajsonpy and are using 1.10.0.
