### ISSUE TITLE
No longer accepts access token

### ISSUE THREAD

**Issue by boberthepker** [alandtse/tesla#190]
Hello,

My Home Assistant instance with this custom component quit working today. Assuming that the token had expired, I refreshed it in the Tesla Tokens app but found no way to force a refresh within the Tesla Custom Component GUI. To get around this I removed the custom component, restarted, added it back, but now I get an error when attempting to authenticate. 

Can anyone suggest next troubleshooting steps? 

I did find another website mentioning that V3 of the Tesla Auth API started in Feb 2022, but since we're in April and no one else is reporting an issue I assume this is not the case.

```
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/tesla_custom/config_flow.py:182
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 1:21:36 PM (3 occurrences)
Last logged: 1:35:00 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 206, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tesla_custom/config_flow.py", line 63, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/tesla_custom/config_flow.py", line 182, in validate_input
    result = await controller.connect(test_login=True)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 393, in connect
    cars = await self.get_vehicles()
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 523, in get_vehicles
    return (await self.api("VEHICLE_LIST"))["response"]
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 171, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 1754, in api
    return await self.__connection.post("", method="get", data=kwargs, url=uri)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 162, in post
    access_token=auth["access_token"], expires_in=auth["expires_in"]
KeyError: 'access_token'
```

**Comment by alandtse** [comment]
You have an old teslajsonpy. Make sure you've updated to the latest version of the component. That should install the latest when you add it. If not, you'll have to manually install it.

**Comment by boberthepker** [comment]
> You have an old teslajsonpy. Make sure you've updated to the latest version of the component. That should install the latest when you add it. If not, you'll have to manually install it.

Correct. That fixed it. I keep forgetting that I have to check HACS UI for updates.

Thank you!
