### ISSUE TITLE
KeyError: 'steering_wheel_heater'

### ISSUE THREAD

**Issue by alandtse** [alandtse/tesla#199]
## Version of the custom_component

2.1.0

## Describe the bug

Vehicles without steering_wheel_heaters result in an error.

## Debug log

```text

2022-04-24 13:43:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/config/custom_components/tesla_custom/tesla_device.py", line 121, in refresh
    self.tesla_device.refresh()
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/homeassistant/heated_steering_wheel.py", line 62, in refresh
    data["steering_wheel_heater"] if data else None
KeyError: 'steering_wheel_heater'
```

**Comment by alandtse** [comment]
2.0.1 has been pulled until this is resolved.
