### ISSUE TITLE
Token broken maybe? where to update token

### ISSUE THREAD

**Issue by icepicknz** [alandtse/tesla#202]
Hi,

Everything has been running perfect since about November, but then I noticed there is an error connecting...
I'm wondering if this is token related and if so where do I update the token as it doesnt allow me to do it in integrations page and I cont find it in configuration file?

Logger: homeassistant.config_entries
Source: custom_components/tesla_custom/__init__.py:156 
Integration: Tesla Custom Integration ([documentation](https://github.com/alandtse/tesla), [issues](https://github.com/alandtse/tesla/issues)) 
First occurred: 3:38:47 PM (1 occurrences) 
Last logged: 3:38:47 PM

Error setting up entry xxx@xxx.com for tesla_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tesla_custom/__init__.py", line 156, in async_setup_entry
    result = await controller.connect(
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 336, in connect
    cars = await self.get_vehicles()
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 467, in get_vehicles
    return (await self.api("VEHICLE_LIST"))["response"]
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 167, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 1194, in api
    return await self.__connection.post("", method="get", data=kwargs, url=uri)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 161, in post
    access_token=auth["access_token"], expires_in=auth["expires_in"]
KeyError: 'access_token'

**Comment by alandtse** [comment]
Update the component to the latest.
