### ISSUE TITLE
teslajsonpy.exceptions.TeslaException: HTTP 406: not_a_JSON_request

### ISSUE THREAD

**Issue by paracetamol32** [alandtse/tesla#231]
## Version of the custom_component

2.0.0

## Describe the bug

Today, the service api is broken.
when calling api i have tis result: Call-service error
No problem before

## Step to reproduce:
go in developper tools - > service.
Call service tesla custom api:

service: tesla_custom.api
data:
  command: CHARGING_AMPS
  parameters:
    path_vars:
      vehicle_id: '{{ state_attr(''binary_sensor.re_volt_online_sensor'', ''id'') }}'
    charging_amps: 15

**Comment by IIDemoniaKII** [comment]
Hello,

Same here since update 2022.7.2

Good luck

Call :

```
service: tesla_custom.api
data:
  command: CHARGING_AMPS
  parameters:
    path_vars:
      vehicle_id: '{{ state_attr(''binary_sensor.stacy_online_sensor'', ''id'') }}'
    charging_amps: >-
      {% if states("sensor.stacy_charging_amps") | int(0) | int(0) <= 0 %}  0
      {%- else -%} {{ states("sensor.stacy_charging_amps") | int(0) }} {%- endif
      %}
```

results :

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 428, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/tesla_custom/services.py", line 56, in async_call_tesla_service
    await api(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 112, in api
    return await controller.api(name=command, path_vars=path_vars, **parameters)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 183, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1803, in api
    return await self.__connection.post(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 164, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 213, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
```


```
Tesla - Puissance recharge = Consigne automatique: Error executing script. Unexpected error for call_service at pos 1:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/tesla_custom/services.py", line 56, in async_call_tesla_service
    await api(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 112, in api
    return await controller.api(name=command, path_vars=path_vars, **parameters)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 183, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1803, in api
    return await self.__connection.post(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 164, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 213, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
```

**Comment by lcorreia007** [comment]
Same here, also after updating to 2022.7.2

**Comment by RicSuzu** [comment]
I am still on version 2022.6.4 and CHARGING_AMPS stopped working for me yesterday.

**Comment by simonwestenholz** [comment]
I can’t make it so much of anything. Open trunk, flash lights, set charge limit, etc. all return the following from the teslajsonpy debug log:
`2022-07-09 17:59:06 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/vehicles/{ID}/command/actuate_trunk {'which_trunk': 'rear'}
2022-07-09 17:59:06 DEBUG (MainThread) [teslajsonpy.connection] 406: {"response":null,"error":"not_a_JSON_request","error_description":""}
2022-07-09 17:59:06 DEBUG (MainThread) [teslajsonpy.controller] Exception: 
api(('ACTUATE_TRUNK',) {'path_vars': {'vehicle_id': {ID}}, 'which_trunk': 'rear', 'wake_if_asleep': True})`

The "not_a_JSON_request" is odd to me...

**Comment by alandtse** [comment]
It's probably a Tesla API change. Until someone figures out a solution, there may be nothing to do except avoiding hammering Tesla's servers and getting blocked. https://github.com/timdorr/tesla-api/issues/594

**Comment by haoboji** [comment]
I think `Content-Type: application/json` is missing in the header in `teslajsonpy`.
https://github.com/zabuldon/teslajsonpy/blob/27ed3c0efc2c7ae8e3a2c7726017529ad7d3d900/teslajsonpy/connection.py#L176

**Comment by haoboji** [comment]
I updated the file at /usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py in my HA docker by changing line 200 from `str(url), data=data, headers=headers, cookies=cookies` to `str(url), json=data, headers=headers, cookies=cookies` and everything seems to be working again.
