### ISSUE TITLE
Calling command service errors out

### ISSUE THREAD

**Issue by pandaedward** [alandtse/tesla#239]
## Version of the custom_component
*2.3.1*

Thanks heaps for the great work! I am attempting to set up an automation with a input button to wake the Tesla up when the button is pressed.

The automation is very simple with an action to invoke the `tesla_custom.api` with command data and parameters as dictionary:

```
- alias: "Attemmpt to wake up Tesla model 3"
  trigger:
    - platform: state
      entity_id: input_button.tesla_wake_up
  action:
    - service: tesla_custom.api
      data:
        command: WAKE_UP
        parameters:
          path_vars:
            vehicle_id: '1490000000000'
            wake_if_asleep: 'True'
```

However there is async error when the automation is triggered:
```
Logger: homeassistant.components.automation.attemmpt_to_wake_up_tesla_model_3
Source: custom_components/tesla_custom/services.py:112
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 5:40:34 PM (2 occurrences)
Last logged: 5:40:34 PM

    Attemmpt to wake up Tesla model 3: Error executing script. Unexpected error for call_service at pos 1:
    While executing automation automation.attemmpt_to_wake_up_tesla_model_3

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/tesla_custom/services.py", line 56, in async_call_tesla_service
    await api(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 112, in api
    return await controller.api(name=command, path_vars=path_vars, **parameters)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 267, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1803, in api
    return await self.__connection.post(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 164, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 213, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
```

The integration is authenticated correctly and all other sensors and switches works perfectly just not the custom service call. Could any of you shed some light in here please?

**Comment by pandaedward** [comment]
The issue actually lies with Tesla and its SIM. Under the hood Tesla wakes up the vehicle by sending a SMS and data or not cell reception is required. 

I confirm by using postman and observe the response from there.
