### ISSUE TITLE
500 error after running through /etc/hosts captcha workaround

### ISSUE THREAD

**Issue by rubin110** [alandtse/tesla#25]
## Version of the custom_component

0.2.1

## Describe the bug

After running through the dirty (in a good way) workaround [described here](https://github.com/alandtse/tesla/issues/20#issuecomment-913810106) for the [Invalid domain for site key bug](https://github.com/alandtse/tesla/issues/20), I hit a 500. I've continued to hit a 500 subsequently each time I restart the add intigration workflow with popping open the proxy page.

Please let me know if you're needing more regarding the logs.

## Debug log

```text
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
    return await cls.handler(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 396, in all_handler
    result = await run_func(test, test_name, resp, self.data, self.query)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/helper.py", line 83, in run_func
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/teslaproxy.py", line 85, in test_url
    code = resp.url.query.get("code")
AttributeError: 'bytes' object has no attribute 'get'
2021-09-09 19:17:45 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
    return await cls.handler(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 396, in all_handler
    result = await run_func(test, test_name, resp, self.data, self.query)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/helper.py", line 83, in run_func
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/teslaproxy.py", line 85, in test_url
    code = resp.url.query.get("code")
AttributeError: 'bytes' object has no attribute 'get'
2021-09-09 19:17:55 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
    return await cls.handler(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 396, in all_handler
    result = await run_func(test, test_name, resp, self.data, self.query)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/helper.py", line 83, in run_func
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/teslaproxy.py", line 85, in test_url
    code = resp.url.query.get("code")
AttributeError: 'bytes' object has no attribute 'get'
2021-09-09 19:18:22 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/config/custom_components/tesla_custom/config_flow.py", line 325, in wrapped
    return await cls.handler(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/auth_capture_proxy.py", line 396, in all_handler
    result = await run_func(test, test_name, resp, self.data, self.query)
  File "/usr/local/lib/python3.9/site-packages/authcaptureproxy/helper.py", line 83, in run_func
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/teslaproxy.py", line 85, in test_url
    code = resp.url.query.get("code")
AttributeError: 'bytes' object has no attribute 'get'

```

![bitmoji](https://sdk.bitmoji.com/render/panel/6e3eb687-79c8-443e-b053-fc574f6a5be9-910473c3-591d-4f8f-a058-cc6dee279770-v1.png?transparent=1&palette=1&width=246)

**Comment by alandtse** [comment]
Thanks for posting and directing people here. We're likely not to solve this since we're transitioning to using refresh tokens only (taken from another app). The plan is to switch this weekend.

Although it's really odd that the query item is a bytes object.

I don't run into this myself with the workaround but I have MFA enabled which forces the auth to a separate page that is processed correctly. Perhaps enabling MFA if you don't have it on already would be a workaround for this 500 error.

**Comment by rubin110** [comment]
Oh ok that's great! I was looking for the section in `core.config_entries` to just add the tokens myself but maybe they've moved somewhere else or haven't been created yet as I haven't completely passed through the initial sign in flow.

Not that it seems to matter now but I do have MFA enabled, and was able to pass my OTP through that flow right before hitting the 500.
