### ISSUE TITLE
response["grid_status"] doesn't exist for non-powerwall solar systems

### ISSUE THREAD

**Issue by mcolyer** [alandtse/tesla#265]
Version: 2.4.3

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tesla_custom/__init__.py", line 150, in async_setup_entry
    result = await controller.connect(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 469, in connect
    await self.update(wake_if_asleep=wake_if_asleep)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1074, in update
    return any(await asyncio.gather(*tasks))
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 991, in _get_and_process_energysite_data
    if response["grid_status"] == "Active":
KeyError: 'grid_status'
```

**Comment by mcolyer** [comment]
Actually, it appears I wasn't running the version I thought I was - I believe this is fixed now.
