### ISSUE TITLE
Unexpected error fetching tesla_custom data: local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by purcell-lab** [alandtse/tesla#324]
## Version of the custom_component

V3.0.2

## Describe the bug

Received this error message in my system logs, unsure if it has effected any functionality.

## Debug log

```text
This error originated from a custom integration.

Logger: custom_components.tesla_custom
Source: custom_components/tesla_custom/__init__.py:346
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 5:59:50 AM (1 occurrences)
Last logged: 5:59:50 AM

Unexpected error fetching tesla_custom data: local variable 'response' referenced before assignment
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tesla_custom/__init__.py", line 346, in _async_update_data
    return await self.controller.update()
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 964, in update
    return any(await asyncio.gather(*tasks))
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 783, in _get_and_process_car_data
    response = await self.get_vehicle_data(
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 512, in get_vehicle_data
    return response
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by skynet01** [comment]
Pretty much the same error, the integration won't start up anymore for some reason. Worked fine until this error showed up 🤷‍♂️
