### ISSUE TITLE
Teslajsonpy exception since installation of release 3.0.2

### ISSUE THREAD

**Issue by jmcollin78** [alandtse/tesla#335]
## Version of the custom_component

3.0.2

## Configuration

Home assistant HAOS, core 2022.11.01

## Describe the bug

Since the update of the Tesla custom component through HACS, all my devices are unavailable and the logs shows the following error.
There is no more description of the error and of what happens really.

## Debug log

```text
2022-11-09 08:20:25.074 ERROR (MainThread) [homeassistant.components.script.reveil_cloucloute] Réveil Cloucloute: Error executing script. Unexpected error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/tesla_custom/services.py", line 55, in async_call_tesla_service
    await api(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 111, in api
    return await controller.api(name=command, path_vars=path_vars, **parameters)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 150, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1431, in api
    return await self.__connection.post(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 160, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 209, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
2022-11-09 08:20:25.089 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 484, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/tesla_custom/services.py", line 55, in async_call_tesla_service
    await api(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 111, in api
    return await controller.api(name=command, path_vars=path_vars, **parameters)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 150, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1431, in api
    return await self.__connection.post(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 160, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 209, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException

```

**Comment by jmcollin78** [comment]
I have clearly seen a message saying "This requires a refresh token be generated by third-party apps to login". A have a refresh token but the configuration of the integration doesn't propose me to set a new refresh token.

Is a new refresh token mandatory when updating from 2.4.4 to 3.0.2 ?
how do we change the refresh token ?

**Comment by alandtse** [comment]
> how do we change the refresh token ?

Remove and readd which was suggested in the breaking changes notes. https://github.com/alandtse/tesla/releases/tag/v3.0.0#Breaking

**Comment by jmcollin78** [comment]
After removing and restarting all is now alright.

I have just loose all my devices and entities :-(

![Capture d’écran 2022-11-09 à 19 24 49](https://user-images.githubusercontent.com/1712374/200910979-2ef3f6b1-cc4b-41e5-8c21-0f696ce22077.png)

**Comment by jmcollin78** [comment]
I there a mapping somewhere where I can find the new entities names ?

**Comment by alandtse** [comment]
> I there a mapping somewhere where I can find the new entities names ?

No. But if you look in Devices you'll see them all.

**Comment by jmcollin78** [comment]
The procedure is to delete the integration and to recreate it with a new Refresh token. Then all works as expected (after you rename many of your entities)
