### ISSUE TITLE
Latest 3.2.0 failed to set up

### ISSUE THREAD

**Issue by pandaedward** [alandtse/tesla#368]
## Configuration

```yaml
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tesla_custom/__init__.py:216
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 17:57:28 (1 occurrences)
Last logged: 17:57:28

Error setting up entry e.pc.yuan@gmail.com for tesla_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tesla_custom/__init__.py", line 216, in async_setup_entry
    cars = await controller.generate_car_objects(wake_if_asleep=wake_if_asleep)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 567, in generate_car_objects
    self._vehicle_data[vin] = await self.get_vehicle_data(
  File "/usr/local/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 512, in get_vehicle_data
    return response
UnboundLocalError: local variable 'response' referenced before assignment

```

## Describe the bug

Home Assistant version: 2022.11.4 vanilla install
OVA

Tried cleaning up the `tesla_custom` folder in `custom_components`, unzip, copied over and starting a fresh set up. Same error is shown. 

## Debug log

I had experienced the issue ever since v3, failed on latest v3.2.0 today hence raising the issue. 

I am falling back to known good version 2.4.4 for now.

**Comment by carleeno** [comment]
this is the same as #324, and will be fixed in the next version with https://github.com/zabuldon/teslajsonpy/pull/365
