### ISSUE TITLE
Getting "vehicle_unavailable" error while driving

### ISSUE THREAD

**Issue by saxtonab14** [alandtse/tesla#434]
I seem to be having an issue with the API timing out once my tesla is put into gear. I am seeing the below error in the logs, and do not see any data updating. I'm trying to use location data while driving mostly, but that doesn't seem to update either. However, once it is put into park, everything works as expected.

Logger: homeassistant.core
Source: custom_components/tesla_custom/climate.py:139
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 12:17:39 AM (2 occurrences)
Last logged: 12:17:53 AM

Error executing service: <ServiceCall climate.set_hvac_mode (c:01GMA3EDBRYF4EDP9N4BWG7YXC): hvac_mode=heat_cool, entity_id=['climate.hvac_climate_system']>
Error executing service: <ServiceCall climate.set_hvac_mode (c:01GMA3ETVFZPR46MEWTAXWRVQG): hvac_mode=heat_cool, entity_id=['climate.hvac_climate_system']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1756, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 207, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/tesla_custom/climate.py", line 139, in async_set_hvac_mode
    await self._car.set_hvac_mode("on")
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 993, in set_hvac_mode
    data = await self._send_command("CLIMATE_ON")
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 759, in _send_command
    raise ex
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 744, in _send_command
    data = await self._controller.api(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1350, in api
    response = await self.__connection.post(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 160, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 208, in __open
    raise TeslaException(resp.status_code, "vehicle_unavailable")
teslajsonpy.exceptions.TeslaException: vehicle_unavailable

**Comment by alandtse** [comment]
@carleeno I think we forgot to catch the new exception...

The issue is we can't connect.  It won't update but we can at least handle the error cleanly.

**Comment by carleeno** [comment]
@alandtse I'm double checking past versions since v3 and it looks like we never had special 408 handling for commands (climate, locks, etc). These are probably things we _do_ want to return an error when it fails, since it's a command sent by a human or automation, not regular polling. I recently added handling so that if a command returns 408 and the car is asleep and `wake_if_asleep` is false, it will not raise the exception since we didn't want to wake it anyway. But `CLIMATE_ON` tries to wake it if asleep so we would always see any final 408 as an error in logs.

@saxtonab14 do you have an automation that turns on climate? Can you check that it's not running repeatedly when you're driving?
