### ISSUE TITLE
"Sensor sensor.bolt_time_charge_complete has a state class and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp"

### ISSUE THREAD

**Issue by Hubro** [alandtse/tesla#480]
## Version of the custom_component

3.9.1 (84f322a9ce212c20ecfe656ddeba6101d439e3a9)

Home Assistant version: 
![image](https://user-images.githubusercontent.com/597206/211314570-3695cd6e-b85b-44a9-8d2e-110f0d917194.png)

## Configuration

![image](https://user-images.githubusercontent.com/597206/211313850-36a4174d-f508-4476-9753-7b2810c52079.png)

I don't have any configuration related to the tesla_custom component, I just installed it and set it up through the UI. Please clarify if I should upload anything here.

## Describe the bug

Any time I try to run a tesla_custom service, I get this error in the UI:

![image](https://user-images.githubusercontent.com/597206/211313498-6206fe49-a2b9-4adf-b676-64062cdf5ef4.png)

In spite of this, data does seem to update. However, none of the services work. I'm unable to operate the HVAC, lock the doors etc.

## Debug log

```text
2023-01-09 13:54:30.108 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2023-01-09 13:54:30.109 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.001 seconds (success: True)
2023-01-09 13:54:30.121 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548424726896] Sensor sensor.bolt_time_charge_complete has a state class and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 116, in _async_press_action
    await self.async_press()
  File "/config/custom_components/tesla_custom/button.py", line 114, in async_press
    await self.update_controller(wake_if_asleep=True, force=True)
  File "/config/custom_components/tesla_custom/base.py", line 95, in update_controller
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 201, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 316, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/base.py", line 40, in refresh
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 562, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 901, in state
    raise ValueError(
ValueError: Sensor sensor.bolt_time_charge_complete has a state class and thus indicating it has a numeric value; however, it has the non-numeric device class: timestamp
```

**Comment by alandtse** [comment]
Please provide the service call that you're using so we can replicate. I'm not seeing any code to set a state_class to the time charge complete sensor.

**Comment by Hubro** [comment]
@alandtse This has been broken on my Home Assistant setup for a couple of weeks. I tried reinstalling the Tesla custom component, upgrading it to the newest version, rebooting the system etc.

However, in the last couple of days it seems to have solved itself, ostensibly after a Home Assistant update (2023.1.4?)

**Comment by alandtse** [comment]
Ok. Let me know if it comes back and we can look again.
