### ISSUE TITLE
Unexpected error fetching tesla_custom data: 'str' object has no attribute 'update'

### ISSUE THREAD

**Issue by llamafilm** [alandtse/tesla#494]
I've been using this integration for a few weeks and just noticed this for the first time today.  All the entities are unavailable and I see this error in the log.  After restarting HA it works fine.  I've now enabled debug logging for `homeassistant.components.tesla_custom` and `teslajsonpy` and I'll post the logs if it happens again.  

I have a Tesla model 3 and a solar panel, but no Powerwall.  Last week I removed the Powerblaster CT clamps from my breaker panel (because they were unreliable), which means the Tesla app no longer receives data about my consumption.  I wonder if that might be relevant here.

```
2023-01-23 09:39:14.758 ERROR (MainThread) [custom_components.tesla_custom] Unexpected error fetching tesla_custom data: 'str' object has no attribute 'update'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tesla_custom/__init__.py", line 346, in _async_update_data
    return await self.controller.update()
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 822, in update
    return any(await asyncio.gather(*tasks))
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 703, in _get_and_process_site_data
    self._site_data[energysite_id].update(response)
AttributeError: 'str' object has no attribute 'update'
```

## Version of the custom_component
3.9.1

**Comment by alandtse** [comment]
Sorry, the PowerBlaster is for your panels? So before you didn't have this issue but now you do but after a restart it went away?

**Comment by llamafilm** [comment]
The Powerblaster was used to measure energy consumption of the house.  (I replaced it with IotaWatt.)  The solar generation is measured by the inverter itself, which sends the data to Tesla's ethernet hub via Zigbee.  That might be a red herring though.  I removed the Powerblaster on January 14 and the issue just started today.
After restarting HA this issue went away.

**Comment by llamafilm** [comment]
Looking at this again, now I'm having a slightly different error but I think it's related.  All my solar entities are unavailable and this time restarting HA does not fix it.  My Tesla vehicle entities are working fine.
```
2023-02-03 21:47:27.112 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/base.py", line 39, in refresh
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 607, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 466, in state
    value = self.native_value
  File "/config/custom_components/tesla_custom/sensor.py", line 406, in native_value
    return round(self._energysite.solar_power)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/energy.py", line 110, in solar_power
    return self._site_data.get("solar_power")
AttributeError: 'str' object has no attribute 'get'
```

I added a debug print there to inspect `_site_data` and I see it's an empty string.

I ran TeslaPy as described [here](https://github.com/zabuldon/teslajsonpy/issues/342) and got this:
```
% python3 cli.py -e <myemailaddress> -z SITE_DATA   
2023-02-03 22:02:34,436 - root - INFO - 2 product(s), 2 selected
Product 0:
Product 1:
{
    "response": ""
}
```

That empty response comes directly from this endpoint: 
`https://owner-api.teslamotors.com/api/1/energy_sites/{{site_id}}/live_status`

In Postman, the product list API works fine, showing 1  vehicle and 1 energy site from this endpoint:
`https://owner-api.teslamotors.com/api/1/products`
Redacted output:
```json
{
    "energy_site_id": xxxxx,
    "resource_type": "solar",
    "id": "xxxxx",
    "asset_site_id": "xxxxxxx",
    "solar_power": 0,
    "solar_type": "pv_panel",
    "storm_mode_enabled": null,
    "powerwall_onboarding_settings_set": null,
    "powerwall_tesla_electric_interested_in": null,
    "sync_grid_alert_enabled": false,
    "breaker_alert_enabled": false,
    "components": {
        "battery": false,
        "solar": true,
        "solar_type": "pv_panel",
        "grid": true,
        "load_meter": true,
        "market_type": "residential"
    }
}
```

**Comment by llamafilm** [comment]
This morning around 10am my solar inverter quit producing power and showed error codes `402`, `434`.  Maybe that's related.  I'll have to call Tesla on Monday to inquire.
