### ISSUE TITLE
AttributeError: 'AsyncConnectionPool' object has no attribute 'arequest'

### ISSUE THREAD

**Issue by kennedyshead** [alandtse/tesla#5]
## Version of the custom_component
Fresh HACS install

## Configuration

```yaml
Add your logs here.
```

## Debug log

```
Traceback (most recent call last):
  File "/home/knutas/anaconda3/envs/hass/lib/python3.8/site-packages/homeassistant-2021.5.0.dev0-py3.8.egg/homeassistant/config_entries.py", line 260, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/home/knutas/.homeassistant/custom_components/tesla_custom/__init__.py", line 127, in async_setup_entry
    result = await controller.connect(
  File "/home/knutas/.homeassistant/deps/lib/python3.8/site-packages/teslajsonpy/controller.py", line 288, in connect
    cars = await self.get_vehicles()
  File "/home/knutas/.homeassistant/deps/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/home/knutas/.homeassistant/deps/lib/python3.8/site-packages/teslajsonpy/controller.py", line 407, in get_vehicles
    return (await self.__connection.get("vehicles"))["response"]
  File "/home/knutas/.homeassistant/deps/lib/python3.8/site-packages/teslajsonpy/connection.py", line 90, in get
    return await self.post(command, "get", None)
  File "/home/knutas/.homeassistant/deps/lib/python3.8/site-packages/teslajsonpy/connection.py", line 161, in post
    return await self.__open(
  File "/home/knutas/.homeassistant/deps/lib/python3.8/site-packages/teslajsonpy/connection.py", line 202, in __open
    resp = await getattr(self.websession, method)(
  File "/home/knutas/anaconda3/envs/hass/lib/python3.8/site-packages/httpx-0.17.1-py3.8.egg/httpx/_client.py", line 1539, in get
    return await self.request(
  File "/home/knutas/anaconda3/envs/hass/lib/python3.8/site-packages/httpx-0.17.1-py3.8.egg/httpx/_client.py", line 1361, in request
    response = await self.send(
  File "/home/knutas/anaconda3/envs/hass/lib/python3.8/site-packages/httpx-0.17.1-py3.8.egg/httpx/_client.py", line 1396, in send
    response = await self._send_handling_auth(
  File "/home/knutas/anaconda3/envs/hass/lib/python3.8/site-packages/httpx-0.17.1-py3.8.egg/httpx/_client.py", line 1434, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/knutas/anaconda3/envs/hass/lib/python3.8/site-packages/httpx-0.17.1-py3.8.egg/httpx/_client.py", line 1466, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/home/knutas/anaconda3/envs/hass/lib/python3.8/site-packages/httpx-0.17.1-py3.8.egg/httpx/_client.py", line 1492, in _send_single_request
    (status_code, headers, stream, ext) = await transport.arequest(
  File "/home/knutas/anaconda3/envs/hass/lib/python3.8/site-packages/httpx-0.17.1-py3.8.egg/httpx/_transports/default.py", line 169, in arequest
    return await self._pool.arequest(
AttributeError: 'AsyncConnectionPool' object has no attribute 'arequest'
```

```text

Add your logs here.

```

**Comment by alandtse** [comment]
Thanks.

What version of httpcore is in your system? It needs to be 0.12.1 < x < 0.13.0
```console
bash-5.0# pip list | grep httpcore
httpcore                         0.12.3
```

**Comment by kennedyshead** [comment]
```
pip list | grep httpcore
httpcore                 0.12.1
```

**Comment by alandtse** [comment]
Closing given 3.0 rewrite.
