### ISSUE TITLE
Issue with Tesla resources unavailable after upgrading Home Assistant to 2023.3.0

### ISSUE THREAD

**Issue by standaloneSA** [alandtse/tesla#521]
This afternoon, I updated to Home Assistant 2023.3.0 and lost all of my metrics and statuses in the Tesla integration. I updated to the latest release of the Tesla integration in HACS and that didn't fix anything. 

Running: 

Home Assistant 2023.3.0 
Supervisor 2023.01.1 
Operating System 9.5

Tesla Release v3.10.0

What information can I get to help debug this?

**Comment by kbrint** [comment]
FWIW, I had a similar issue, but yesterday on 2023.2.5.  It's possible that the update was a trigger, but not the root cause.

**Comment by standaloneSA** [comment]
@kbrint Did it self-resolve, or did you have to do anything to fix it?

**Comment by kbrint** [comment]
Neither.  Still busted.

Restarting Home Assistant, removing and re-adding the integration did not work.  I tried regenerating a new access key.  Nothing has worked, and the Home Assistant "Device" for the car has vanished.    The only two devices I have now in the Tesla Custom integration are "Charging rate" and "My Home" (for solar).

**Comment by standaloneSA** [comment]
Okay coo. So, I enabled debug mode on the plugin and tried to remote start my vehicle. 

```
2023-03-02 01:29:26.842 DEBUG (MainThread) [teslajsonpy.car] Sending command: REMOTE_START
2023-03-02 01:29:26.843 DEBUG (MainThread) [teslajsonpy.controller] 71315: Sending wake request with deadline of: 1677738626
2023-03-02 01:29:26.843 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 7:35:33
2023-03-02 01:29:26.843 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/vehicles/<MYID>/wake_up {}
2023-03-02 01:29:27.165 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":{"id":3744420255818889,"user_id":344313,"vehicle_id":<MYID>,"vin":"<MY VIN>","display_name":"Tess 3.0","option_codes":"AD15,MDL3,PBSB,RENA,BT37,ID3W,RF3G,S3PB,DRLH,DV2W,W39B,APF0,COUS,BC3B,CH07,PC30,FC3P,FG31,GLFR,HL31,HM31,IL31,LTPB,MR31,FM3B,RS3H,SA3P,STCP,SC04,SU3C,T3CA,TW00,TM00,UT3P,WR00,AU3P,APH3,AF00,ZCST,MI00,CDM0","color":null,"access_type":"OWNER","tokens":["<TOKEN1>","<TOKEN2>"],"state":"asleep","in_service":false,"id_s":"<ID>","calendar_enabled":true,"api_version":52,"backseat_token":null,"backseat_token_updated_at":null}}
2023-03-02 01:29:29.166 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 7:35:30
```

So you can see, it's communicating with the API properly. It makes several calls to the owner-api, each of which succeeds with a 200, then at the end: 

```
2023-03-02 01:29:42.184 DEBUG (MainThread) [teslajsonpy.controller] 71315: Changing car_online from False to True
2023-03-02 01:29:42.184 DEBUG (MainThread) [teslajsonpy.controller] 71315: Resetting last_wake_up_time to: 1677738582
2023-03-02 01:29:42.184 DEBUG (MainThread) [teslajsonpy.controller] 71315: Wakeup took 15 seconds, state: online
2023-03-02 01:29:42.185 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 7:35:17
2023-03-02 01:29:42.185 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/vehicles/3744420255818889/command/remote_start_drive {}
2023-03-02 01:29:42.515 DEBUG (MainThread) [teslajsonpy.connection] 200: {"response":{"result":true,"reason":""}}
2023-03-02 01:29:42.516 DEBUG (MainThread) [teslajsonpy.car] Response from command REMOTE_START: {'response': {'result': True, 'reason': ''}}
2023-03-02 01:29:42.516 DEBUG (MainThread) [teslajsonpy.car] Remote start response: {'result': True, 'reason': ''}
2023-03-02 01:29:42.517 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall button.press (c:01GTGG5S5P416D7XB9MSFN5PGX): entity_id=['button.tess_3_0_remote_start']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1826, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 116, in _async_press_action
    await self.async_press()
  File "/config/custom_components/tesla_custom/button.py", line 164, in async_press
    await self._car.remote_start()
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/car.py", line 1206, in remote_start
    self._vehicle_data["vehicle_state"].update({"remote_start": True})
KeyError: 'vehicle_state'
```
It then successfully gets vehicle_data  and prints out a bunch of parsed information from that call. I haven't seen any API calls fail. 

The code being called there in the teslajsonpy module is: 
```
    async def remote_start(self) -> None:
        """Remote start."""
        data = await self._send_command("REMOTE_START")

        if data and data["response"]:
            _LOGGER.debug("Remote start response: %s", data["response"])
            result = data["response"]["result"]
            reason = data["response"]["reason"]
            if result is False:
                _LOGGER.debug("Error calling remote start: %s", reason)
            else:
                self._vehicle_data["vehicle_state"].update({"remote_start": True})
```
(from https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/car.py#L1195) 

 I'm not sure what changed, exactly, but it seems like the vehicle_data's vehicle_state isn't being set. 

Looking at the json response from the 'get https://owner-api.teslamotors.com/.../vehicle_data', I see vehicle_state being returned: 

```
[msimmons@mediabox tmp]$
[msimmons@mediabox tmp]$ cat t | jq '.response.vehicle_state'
{
  "api_version": 52,
  "autopark_state_v3": "ready",
  "autopark_style": "dead_man",
  "calendar_supported": true,
  "car_version": "2023.2.12 a734fb860b32",
  "center_display_state": 0,
  "dashcam_clip_save_available": true,
  "dashcam_state": "Recording",
  "df": 0,
  "dr": 0,
  "fd_window": 0,
  "feature_bitmask": "dffbff,0",
  "fp_window": 0,
  "ft": 0,
  "homelink_device_count": 1,
  "homelink_nearby": true,
  "is_user_present": false,
  "last_autopark_error": "no_error",
  "locked": false,
  "media_info": {
...
```


ANNND while I was debugging this, it started working again. 
 Sigh. 

Did yours too @kbrint ? 

Maybe it was a problem with the Tesla API? My phone app was working fine. I don't know what else it could have been.

**Comment by kbrint** [comment]
My phone has worked too.  My token is working according to the logs, and I don't think it's an auth issue.  I get 200 HTTP status responses for Energy related queries.  I get a VIN in the response to `/api/1/products`:

`2023-03-01 23:23:24.701 DEBUG (MainThread) [teslajsonpy.connection] get: https://owner-api.teslamotors.com/api/1/products {}
`

There are some relevant results..  I can see the VIN:

`....  {"response":[{"id":14xxxxx,"user_id":3xxxx,"vehicle_id":1xxxxxxxxx,"vin":"5xxxxxxxxxx","display_name":""
`

**Comment by kbrint** [comment]
This looks relevant:

`
2023-03-01 23:26:39.718 DEBUG (MainThread) [teslajsonpy.connection] 408: {"response":null,"error":"vehicle unavailable: {:error=>\"vehicle unavailable:\"}","error_description":""}
`

I do have the HA component setup (just now) to "Force cars awake on startup".  No change AFAICT.

**Comment by kbrint** [comment]
My car showed offline after I enabled the debug logs:  `... "state":"offline","in_service":false, ...`

Resetting the MCU fixed it.
