### ISSUE TITLE
orjson.JSONDecodeError: Input must be bytes, bytearray, memoryview, or str: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by alandtse** [alandtse/tesla#525]
## Version of the custom_component
3.10.1

## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tesla_custom/__init__.py:157
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 10:43:40 PM (2 occurrences)
Last logged: 10:54:13 PM

Error setting up entry alandtse@gmail.com for tesla_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tesla_custom/__init__.py", line 157, in async_setup_entry
    result = await controller.connect(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 197, in connect
    self._product_list = await self.get_product_list()
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 291, in get_product_list
    return (await self.api("PRODUCT_LIST"))["response"]
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1323, in api
    return await self.__post_with_retries("", method=method, data=kwargs, url=uri)
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1333, in __post_with_retries
    return await self.__connection.post(command, method=method, data=data, url=url)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 161, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 211, in __open
    data = orjson.loads(resp)  # pylint: disable=no-member
orjson.JSONDecodeError: Input must be bytes, bytearray, memoryview, or str: line 1 column 1 (char 0)

```

**Comment by alandtse** [comment]
3.10.1 pulled for now.

**Comment by bdraco** [comment]
Probably needs any `XXXX.json()` that was changed to `orjson.loads(XXXX)` to be `orjson.loads(XXXX.text())`

**Comment by alandtse** [comment]
Yup, just realized my test env wasn't loading the new teslajsonpy when I was testing.
