### ISSUE TITLE
Send address to vehicle

### ISSUE THREAD

**Issue by brian-gates** [alandtse/tesla#541]
[iPhones can send addresses to a Tesla](https://tesla-info.com/blog/tesla-send-destination-to-car.php). I would love to be able to send addresses from Home Assistant.

**Comment by alandtse** [comment]
Feel free to submit a PR. https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/endpoints.json

**Comment by brian-gates** [comment]
@alandtse https://github.com/zabuldon/teslajsonpy/pull/399 was merged, is there anything needed in this repo to upgrade or support it?

**Comment by alandtse** [comment]
Yes. Someone needs to do a PR to bump teslajsonpy. There's tons of examples.

**Comment by brian-gates** [comment]
Looks like it [auto versions based on semver](https://github.com/zabuldon/teslajsonpy/commit/0a7efb0e2d357aba201a9b75f87659af2813a551) per the [semantic_release action](https://github.com/zabuldon/teslajsonpy/actions/workflows/semantic_release.yml)?

Do we just need to merge to main here? https://github.com/zabuldon/teslajsonpy/pull/400

**Comment by alandtse** [comment]
Yah I forgot I hadn't merged the version bump PR last night due to the ci testing so it wasn't released yet.

**Comment by kalavo** [comment]
How'd you go Brian?

Bumped required to 3.7.5 in manifest.json at this end and the call above now working perfectly for me :)

Thank you both for your help 👍

**Comment by brian-gates** [comment]
@kalavo, I gotta [update the dependency](https://github.com/alandtse/tesla/pull/542#issuecomment-1478779338 ) but I don't have a proper python environment with poetry setup. I was having some issues getting it all setup. I will definitely come back to this, but it might be a few days.

**Comment by brian-gates** [comment]
Ah, I believe I found where, under `/developer-tools/service`

**Comment by kalavo** [comment]
Quickest way to start testing is to go to Developer Tools, then click Services.

Should be able to copy, paste above with a few minor changes.

binary_sensor.online was the default when I installed the Tesla api. It contains the vehicle_id, vin, id and state. You can just copy and paste the id instead if you prefer. If you can’t find it, sing out.

locale you probably need en-us

and address, well up to you…
11163 Santa Monica Blvd, Los Angeles, CA 90025 ? :)

**Comment by brian-gates** [comment]
It worked!

It took me a while to find the vehicle id. For posterity, I found it by going to my vehicle's device page (settings > devices > search), clicking the "Online" sensor, then expanding the Attributes section. It's the `ID` attribute (confusingly, not `Vehicle ID`).

Using the incorrect id results in an unhelpful error message. 

> Failed to call service tesla_custom.api. Unknown error

The logs were not much more informative.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tesla_custom/services.py:110
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:30:24 PM (4 occurrences)
Last logged: 9:34:06 PM

[140003098495248] Error handling message: Unknown error (unknown_error) Brian from 192.168.0.25 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 647, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/tesla_custom/services.py", line 54, in async_call_tesla_service
    await api(service_call)
  File "/config/custom_components/tesla_custom/services.py", line 110, in api
    path_vars = parameters.pop(ATTR_PATH_VARS)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1323, in api
    return await self.__post_with_retries("", method=method, data=kwargs, url=uri)
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1333, in __post_with_retries
    return await self.__connection.post(command, method=method, data=data, url=url)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 161, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 210, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
```

**Comment by kalavo** [comment]
Awesome! Glad you got it working! Happy navigating :)

**Comment by alandtse** [comment]
Please consider updating the wiki if you have a good example. Others can then benefit from this thread which will quickly get buried.

**Comment by brian-gates** [comment]
> Please consider updating the wiki if you have a good example. Others can then benefit from this thread which will quickly get buried.

Done
https://github.com/alandtse/tesla/wiki/Share

**Comment by alandtse** [comment]
Thanks, you're awesome!
