### ISSUE TITLE
Cancelation during `generate_car_objects` can be raised into `async_setup_entry` which causes setup to fail

### ISSUE THREAD

**Issue by bdraco** [alandtse/tesla#553]
Cancelation during `generate_car_objects` can be raised into `async_setup_entry` which causes setup to fail

I think this is caused by a timeout somewhere but I haven't had a chance to dig in and its getting late so I wanted to document it and will look more tomorrow.

```
2023-03-26 08:18:51.741 DEBUG (MainThread) [teslajsonpy.connection] 408: {"response":null,"error":"vehicle unavailable: {:error=>\"vehicle unavailable:\"}","error_description":""}
2023-03-26 08:18:55.952 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxx@koston.org for tesla_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tesla_custom/__init__.py", line 228, in async_setup_entry
    cars = await controller.generate_car_objects(wake_if_asleep=wake_if_asleep)
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 382, in generate_car_objects
    self._vehicle_data[vin] = await self.get_vehicle_data(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 307, in get_vehicle_data
    await self.api(
  File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1336, in api
    return await self.__post_with_retries("", method=method, data=kwargs, url=uri)
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 58, in __call__
    await self.sleep(do)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError
```

**Comment by bdraco** [comment]
I'm not sure what is canceling the inner task but its being raised all the way back up

**Comment by alandtse** [comment]
Should I wait for this before the next release?

**Comment by bdraco** [comment]
I expect it's probably been around for a while and I haven't found the root cause even after some digging since the trace gets a bit light after it ends up in tenacity.

Probably shouldn't wait on this as I haven't been able to get it to happen again so it's probably going to take a while to solve.

**Comment by bdraco** [comment]
This might have been a bug in core or cpython that was already fixed.

I can't replicate this anymore.
