### ISSUE TITLE
unable to setup up integration

### ISSUE THREAD

**Issue by goOFYy** [alandtse/tesla#594]
## Version of the custom_component
V3.12.1

## Describe the bug
i am having a bug trying to setup the integration. i am running docker HA 2023.4.6, tesla custom integration with HACS latest version both. this was working and it stopped, i though the refresh token had died so i generated a new one and tried again.
i am getting this error in the logs. i am using the teslatoken app for androi

## Debug log

```text

Logger: homeassistant.config_entries
Source: custom_components/tesla_custom/init.py:164
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 18:49:27 (1 occurrences)
Last logged: 18:49:27

Error setting up entry ******@gmail.com for tesla_custom
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
result = func(*args)
File "/usr/local/lib/python3.10/ssl.py", line 917, in read
v = self._sslobj.read(len)
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2548)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/tesla_custom/init.py", line 164, in async_setup_entry
result = await controller.connect(
File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 197, in connect
self._product_list = await self.get_product_list()
File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 291, in get_product_list
return (await self.api("PRODUCT_LIST"))["response"]
File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1336, in api
return await self.__post_with_retries("", method=method, data=kwargs, url=uri)
File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
return await fn(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 47, in call
do = self.iter(retry_state=retry_state)
File "/usr/local/lib/python3.10/site-packages/tenacity/init.py", line 314, in iter
return fut.result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
return self.__get_result()
File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
raise self._exception
File "/usr/local/lib/python3.10/site-packages/tenacity/_asyncio.py", line 50, in call
result = await fn(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/teslajsonpy/controller.py", line 1346, in __post_with_retries
return await self.__connection.post(command, method=method, data=data, url=url)
File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 125, in post
auth = await self.refresh_access_token(refresh_token=self.refresh_token)
File "/usr/local/lib/python3.10/site-packages/teslajsonpy/connection.py", line 553, in refresh_access_token
auth = await self.websession.post(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
return await self.request(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
return await self.send(request, auth=auth, follow_redirects=follow_redirects)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
response = await self._send_handling_auth(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
response = await self._send_handling_redirects(
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
response = await self._send_single_request(request)
File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
response = await transport.handle_async_request(request)
File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
resp = await self._pool.handle_async_request(req)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
raise exc
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
response = await connection.handle_async_request(request)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
return await self._connection.handle_async_request(request)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
raise exc
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
) = await self._receive_response_headers(**kwargs)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
event = await self._receive_event(timeout=timeout)
File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
data = await self._network_stream.read(
File "/usr/local/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 34, in read
return await self._stream.receive(max_bytes=max_bytes)
File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 195, in receive
data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
File "/usr/local/lib/python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
data = await self.transport_stream.receive()
File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
await self._protocol.read_event.wait()
File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
await fut
asyncio.exceptions.CancelledError```
.

```

**Comment by alandtse** [comment]
There's something wrong at the SSL layer on your machine. We have no control over this as it's outside of our code. The docker image may need to have some packages updated.

**Comment by goOFYy** [comment]
Yes i figured it out host was using a VPN and that blocked the SSL
