### ISSUE TITLE
KeyError: 'site_name' - Can't configure component with only solar panels 

### ISSUE THREAD

**Issue by mcolyer** [alandtse/tesla#62]
## Version of the custom_component

1.1.0

## Configuration

```yaml
```

## Describe the bug

When attempting to configure the integration it fails with this (and yes I put the correct token in the window):

![image](https://user-images.githubusercontent.com/1424/137010722-7dcf3715-8ae6-4a76-927d-1dddf57a2e08.png)

I only have a solar system (no car), I think it's related to this: https://github.com/alandtse/tesla/pull/58. Maybe @giachello knows what's going on?

## Debug log

```text
2021-10-12 11:34:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 198, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tesla_custom/config_flow.py", line 56, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/tesla_custom/config_flow.py", line 160, in validate_input
    result = await controller.connect(test_login=True)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 349, in connect
    self.__energysite_name[energysite_id] = energysite["site_name"]
KeyError: 'site_name'

```

**Comment by alandtse** [comment]
@mcolyer Just to confirm, have you created a name for your energy site? Don't create it if you haven't but it may explain why you got the error. Assuming that's the cause, the most likely fix will be to handle your situation so it'd be great if you could test it once we have it ready.

**Comment by alandtse** [comment]
Oops. Didn't realize I could close this using a dependency merge.

**Comment by pickerin** [comment]
Just wanted to add a comment:
1) This bug is encountered even if you have vehicles, if you have a Solar system
2) Definitely because the default name of your home is "My Home", and it must be returning NULL instead of "My Home"
3) Tapping on the name "My Home" in the Tesla app will allow you to change the name (while viewing your Solar)

Once the name is changed, this error disappears in the integration.

**Comment by mcolyer** [comment]
It works perfectly, thanks!
