### ISSUE TITLE
KeyError: After adding 2nd vehicle

### ISSUE THREAD

**Issue by purcell-lab** [alandtse/tesla#636]
## Describe the bug

I have just added a 2nd vehicle to my Tesla account and the integration doesn't handle this very gracefully, issuing  KeyError with the new VIN.

After reloading the integration, it detects the 2nd vehicle and everything is fine, new device and entities appear as expected.

## Debug log

```text
This error originated from a custom integration.

Logger: custom_components.tesla_custom
Source: custom_components/tesla_custom/__init__.py:437
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 10:13:18 AM (225 occurrences)
Last logged: 10:55:06 AM

Unexpected error fetching tesla_custom data: 'VINof2ndVehicle'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/__init__.py", line 437, in _async_update_data
    return await self.controller.update(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 756, in update
    self.cars[car["vin"]].update_car_info(car)
    ~~~~~~~~~^^^^^^^^^^^^
KeyError: 'VINof2ndVehicle'

```

## Configuration

![image](https://github.com/alandtse/tesla/assets/79175134/acb96b47-7d79-498b-9635-8223fe886cb7)

**Comment by purcell-lab** [comment]
## Status update — May 2026

**Findings**

This is from June 2023 and hasn't seen any traffic since. As far as I can tell from a current scan of the integration:

- The exact line in the original traceback (`self.cars[car["vin"]].update_car_info(car)` at `teslajsonpy/controller.py:756`) has been refactored across multiple `teslajsonpy` releases since v3.13.x, so the line number and surrounding code have moved.
- I can't reproduce this on the current release stack (Tesla Custom Integration `v3.26.0` published May 2026 + current `teslajsonpy`) — adding a vehicle now seems to either succeed cleanly or fail with a clearer error.
- Similar but distinct `KeyError`s (`KeyError: 'vehicle_state'` in [#555](https://github.com/alandtse/tesla/issues/555), `KeyError: 'charge_state'` in [#771](https://github.com/alandtse/tesla/issues/771)) point to a general theme — `teslajsonpy` doesn't always tolerate partial / cold-vehicle payloads where some top-level keys are missing.

**Proposed way forward**

1. **Close as stale / fixed-by-refactor**, on the basis that the originally-reported line is gone and I (the OP) can no longer reproduce. If anyone can reproduce on `v3.26.0+`, please drop a fresh debug log and we'll re-open with a current traceback.
2. **Defensive fix in `teslajsonpy` (low priority).** As a general hardening, the `self.cars[car["vin"]]` access should be `.get(car["vin"])` with a clear log+skip when the VIN isn't already in the dict. That covers this case and the broader family of "vehicle appeared mid-poll" race conditions.
3. **Workaround for anyone who hits this on an older version** — as noted in the original report, reloading the integration after adding the 2nd vehicle gets you back to a clean state.

I'll defer to @alandtse on whether to close or hold open for the defensive fix.
