### ISSUE TITLE
TypeError: float() argument must be a string or a real number, not 'NoneType' on float(self._car.active_route_minutes_to_arrival)

### ISSUE THREAD

**Issue by ehendrix23** [alandtse/tesla#661]
## Version of the custom_component
3.15.0

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

Getting traceback errors in log after updating to 3.15.0.
I have a feeling this might have something to do with no destination set or even just car being asleep right now.

## Debug log

```text

2023-07-08 00:14:59.154 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/base.py", line 40, in refresh
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 813, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/sensor.py", line 710, in extra_state_attributes
    float(self._car.active_route_minutes_to_arrival), 2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
2023-07-08 00:15:03.153 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/base.py", line 40, in refresh
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 813, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/sensor.py", line 710, in extra_state_attributes
    float(self._car.active_route_minutes_to_arrival), 2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'

```

**Comment by MrAshieB** [comment]
Exact same issue as of v3.15.0. Reoccurs every 10-20 seconds or so...

`Logger: homeassistant
Source: custom_components/tesla_custom/sensor.py:710
Integration: Tesla Custom Integration ([documentation](https://github.com/alandtse/tesla/wiki), [issues](https://github.com/alandtse/tesla/issues))
First occurred: 08:37:28 (22 occurrences)
Last logged: 08:41:00

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
    update_callback()
  File "/config/custom_components/tesla_custom/base.py", line 40, in refresh
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 813, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/sensor.py", line 710, in extra_state_attributes
    float(self._car.active_route_minutes_to_arrival), 2
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'`

**Comment by buhito81** [comment]
Makes one think, who pushed 3.15????

**Comment by alandtse** [comment]
> Makes one think, who pushed 3.15????

That isn't helpful. You're not welcome here anymore.

**Comment by alandtse** [comment]
@InTheDaylight14 FYI. Need to catch the None.

**Comment by ehendrix23** [comment]
Thank you for quick fix!

**Comment by MrAshieB** [comment]
100% - thank you @alandtse for being on it!
