### ISSUE TITLE
Error setting up integration - unexpected character: orjson.JSONDecodeError

### ISSUE THREAD

**Issue by onkelfarmor** [alandtse/tesla#690]
## Version of the custom_component: 

3.15.2

## Describe the bug

Error setting up integration. I have tried with two different accounts and several times I have deleted the integration, restarted, reinstalled, restarted and trying adding the integration again. Also tried manually downloading files to custom components folder.

## Debug log

Logger: homeassistant.config_entries
Source: custom_components/tesla_custom/__init__.py:165
Integration: Tesla Custom Integration (documentation, issues)
First occurred: 14.13.23 (1 occurrences)
Last logged: 14.13.23

Error setting up entry xxxxxxxxx@me.com for tesla_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/__init__.py", line 165, in async_setup_entry
    result = await controller.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 202, in connect
    self._product_list = await self.get_product_list()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 296, in get_product_list
    return (await self.api("PRODUCT_LIST"))["response"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 1347, in api
    return await self.__post_with_retries_except_unavailable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/controller.py", line 1379, in __post_with_retries_except_unavailable
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/connection.py", line 125, in post
    auth = await self.refresh_access_token(refresh_token=self.refresh_token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/teslajsonpy/connection.py", line 560, in refresh_access_token
    return orjson.loads(auth.text)  # pylint: disable=no-member
           ^^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)

**Comment by alandtse** [comment]
Looks like the switch to orson means we have to catch orson's error. Happy to take a PR.

Regardless, the error is because it's not accepting the auth token that is being provided. Please verify you are entering the `refresh token` and not the `access token`.

**Comment by onkelfarmor** [comment]
After the update I still can't authenticate:

```
2023-08-28 19:39:08.852 DEBUG (MainThread) [custom_components.tesla_custom.config_flow] Credentials successfully connected to the Tesla API
2023-08-28 19:39:08.859 DEBUG (MainThread) [teslajsonpy.controller] 402 endpoints loaded
2023-08-28 19:39:08.860 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in -19598 days, 4:20:52
2023-08-28 19:39:08.860 DEBUG (MainThread) [teslajsonpy.connection] Oauth expiration detected
2023-08-28 19:39:08.860 DEBUG (MainThread) [teslajsonpy.connection] Refreshing access token with refresh_token
2023-08-28 19:39:08.940 DEBUG (MainThread) [teslajsonpy.connection] Received bad auth response: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;token" on this server.<P>
Reference&#32;&#35;18&#46;4d68dd58&#46;1693244348&#46;15146da7
</BODY>
</HTML>
2023-08-28 19:39:08.941 DEBUG (MainThread) [teslajsonpy.connection] Unable to refresh sso oauth token
2023-08-28 19:39:10.684 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in -19598 days, 4:20:50
2023-08-28 19:39:10.685 DEBUG (MainThread) [teslajsonpy.connection] Oauth expiration detected
2023-08-28 19:39:10.685 DEBUG (MainThread) [teslajsonpy.connection] Refreshing access token with refresh_token
2023-08-28 19:39:10.763 DEBUG (MainThread) [teslajsonpy.connection] Received bad auth response: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;token" on this server.<P>
Reference&#32;&#35;18&#46;4d68dd58&#46;1693244350&#46;1514717e
</BODY>
</HTML>
2023-08-28 19:39:10.763 DEBUG (MainThread) [teslajsonpy.connection] Unable to refresh sso oauth token
2023-08-28 19:39:13.559 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in -19598 days, 4:20:47
2023-08-28 19:39:13.559 DEBUG (MainThread) [teslajsonpy.connection] Oauth expiration detected
2023-08-28 19:39:13.560 DEBUG (MainThread) [teslajsonpy.connection] Refreshing access token with refresh_token
2023-08-28 19:39:13.616 DEBUG (MainThread) [teslajsonpy.connection] Received bad auth response: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;token" on this server.<P>
Reference&#32;&#35;18&#46;4d68dd58&#46;1693244353&#46;151477d4
</BODY>
</HTML>
2023-08-28 19:39:13.617 DEBUG (MainThread) [teslajsonpy.connection] Unable to refresh sso oauth token
2023-08-28 19:39:16.683 WARNING (SyncWorker_0) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 875260. Some data will be missing from sensor entities.
2023-08-28 19:39:16.797 WARNING (SyncWorker_0) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 875644. Some data will be missing from sensor entities.
2023-08-28 19:39:17.922 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in -19598 days, 4:20:43
2023-08-28 19:39:17.922 DEBUG (MainThread) [teslajsonpy.connection] Oauth expiration detected
2023-08-28 19:39:17.923 DEBUG (MainThread) [teslajsonpy.connection] Refreshing access token with refresh_token
2023-08-28 19:39:17.992 DEBUG (MainThread) [teslajsonpy.connection] Received bad auth response: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;token" on this server.<P>
Reference&#32;&#35;18&#46;4d68dd58&#46;1693244357&#46;1514809e
</BODY>
</HTML>
2023-08-28 19:39:17.993 DEBUG (MainThread) [teslajsonpy.connection] Unable to refresh sso oauth token
2023-08-28 19:39:23.862 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in -19598 days, 4:20:37
2023-08-28 19:39:23.862 DEBUG (MainThread) [teslajsonpy.connection] Oauth expiration detected
2023-08-28 19:39:23.862 DEBUG (MainThread) [teslajsonpy.connection] Refreshing access token with refresh_token
2023-08-28 19:39:23.945 DEBUG (MainThread) [teslajsonpy.connection] Received bad auth response: <HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
You don't have permission to access "http&#58;&#47;&#47;auth&#46;tesla&#46;com&#47;oauth2&#47;v3&#47;token" on this server.<P>
Reference&#32;&#35;18&#46;4d68dd58&#46;1693244363&#46;15148cc1
</BODY>
</HTML>
2023-08-28 19:39:23.945 DEBUG (MainThread) [teslajsonpy.connection] Unable to refresh sso oauth token
2023-08-28 19:39:23.946 WARNING (MainThread) [homeassistant.config_entries] Config entry 'mortenbaden@me.com' for tesla_custom integration could not authenticate
```

**Comment by onkelfarmor** [comment]
@alandtse is it possible to reopen the issue?

**Comment by alandtse** [comment]
It's a different issue so it needs to be new. The log is clearly saying there's a permission error. Tesla may have changed the API or it's blocking your credentials.

**Comment by onkelfarmor** [comment]
> It's a different issue so it needs to be new. The log is clearly saying there's a permission error. Tesla may have changed the API or it's blocking your credentials.

@alandtse it is actually the same issue, just a new error text after you updated the plugin. But I make a new.
