### ISSUE TITLE
HACS Custom Tesla not working since update 2023.10.0

### ISSUE THREAD

**Issue by BliXem1** [alandtse/tesla#722]
Since the update of the HA core your custom Tesla HACS isn't working:

Logger: homeassistant.setup
Source: setup.py:215
First occurred: 16:27:06 (1 occurrences)
Last logged: 16:27:06
Setup failed for custom integration tesla_custom: Unable to import component: No module named 'authcaptureproxy'

Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tesla_custom/__init__.py", line 25, in <module>
    from teslajsonpy import Controller as TeslaAPI
  File "/config/lsiopy/lib/python3.11/site-packages/teslajsonpy/__init__.py", line 18, in <module>
    from teslajsonpy.teslaproxy import TeslaProxy
  File "/config/lsiopy/lib/python3.11/site-packages/teslajsonpy/teslaproxy.py", line 17, in <module>
    from authcaptureproxy import AuthCaptureProxy, return_timer_countdown_refresh_html
ModuleNotFoundError: No module named 'authcaptureproxy'

Any idea how I/we can fix this?

**Comment by sbyx** [comment]
@alandtse having the same trouble. Can you please elaborate a bit more. I removed and readded it in hacs and restarted but it didn't change anything.

**Comment by alandtse** [comment]
You'll need to review your HA logs as it will talk about the attempts to install dependencies. However, if it fails to install it you'll need to figure out how to install manually. That is in the FAQ.

**Comment by akballow** [comment]
Just FYI this issue is happening to me. Closing this issue was pretty lame too. I first went to this github to see if someone else opened an issue and did not notice but I had my doubts so ofcourse I look up the same issue and to my surprise the owner closed it. Wow

**Comment by sbyx** [comment]
Got it working now the following way:

1. Stop HA
2. Rename (and later delete) "deps" directory
3. Start HA

HA was rebuilding the deps-directory and it started working again.
