### ISSUE TITLE
New tesla integration wont load

### ISSUE THREAD

**Issue by GSV3MiaC** [alandtse/tesla#733]
I have updated the integration files following the API change but the integration fails to load (nor can I delete it, unloaded) with the log messages

"Logger: homeassistant.loader
Source: custom_components/tesla_custom/__init__.py:52
Integration: Tesla Custom Integration ([documentation](https://github.com/alandtse/tesla/wiki), [issues](https://github.com/alandtse/tesla/issues))
First occurred: 8:37:28 PM (4 occurrences)
Last logged: 8:41:05 PM

Unexpected exception importing component custom_components.tesla_custom
Unexpected exception importing platform custom_components.tesla_custom.application_credentials
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tesla_custom/__init__.py", line 52, in <module>
    CONFIG_SCHEMA = cv.empty_config_schema(DOMAIN)
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'empty_config_schema'"

And some more logs:
"
Logger: aiohttp.server
Source: loader.py:767
First occurred: 8:41:05 PM (1 occurrences)
Last logged: 8:41:05 PM

Error handling request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 760, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tesla_custom/__init__.py", line 52, in <module>
    CONFIG_SCHEMA = cv.empty_config_schema(DOMAIN)
AttributeError: module 'homeassistant.helpers.config_validation' has no attribute 'empty_config_schema'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 67, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 86, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1076, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 767, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.tesla_custom"

OK, I am running a somewhat elderly version of HA under docker on a raspberry Pi, which I am reluctant to mess with, but maybe I need to update more than just the Tesla integration?

I would cheerfully delete it and reinstall, but delete appears to not be an option if I can't load it. Help Please!!

**Comment by GSV3MiaC** [comment]
OK, having waded thru the changelogs it looks like I need a newer version of HA core (23.6.0 or later) to actually run the fixed version of the tesla integration. I will grit my teeth and update
