### ISSUE TITLE
Unable to auth to tesla: 'Controller' object has no attribute 'get_oauth_url'

### ISSUE THREAD

**Issue by xac1d** [alandtse/tesla#8]
I installed HACS, installed this repository and the tesla custom component and restarted HA. after restarting and trying to add the integration, i'm getting the following error at the part where it says "The next step will forward to the proxy for Tesla authentication. Tesla protects the login with a web application firewall (WAF) which may require a refresh to get or receive data. Please be cautious with multiple refreshes in a short period of time": Unknown error occured.

Checking XHR requests the POST to api/config/config_entries/flow/<string> is getting a 500 back (500 Internal Server Error - Server got itself in trouble) 

Version | core-2021.4.6
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.86
CPU Architecture | x86_64
Timezone | America/New_YorK

`2021-05-01 12:57:32 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 107, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 156, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 214, in _async_handle_step
result: dict = await getattr(flow, method)(user_input)
File "/config/custom_components/tesla_custom/config_flow.py", line 72, in async_step_user
return await self.async_step_start_oauth()
File "/config/custom_components/tesla_custom/config_flow.py", line 86, in async_step_start_oauth
host_url: URL = self.controller.get_oauth_url()
AttributeError: 'Controller' object has no attribute 'get_oauth_url'`

**Comment by xac1d** [comment]
*shrug* did it again and it worked fine. thanks!
