### ISSUE TITLE
Can't upgrade to v3.19.6 via HACS

### ISSUE THREAD

**Issue by mcc05** [alandtse/tesla#817]
Issues reported <Integration alandtse/tesla> No assets found for release 'tags/v3.19.6'

**Comment by alandtse** [comment]
It's not released yet.

**Comment by mcc05** [comment]
Sorry must be a bug in HACS that it shows up for download :)

**Comment by alandtse** [comment]
Yah it's new behavior I believe with experimental; I raised an issue.

**Comment by mcc05** [comment]
Debug log from HACS

`2024-01-10 15:33:26.778 INFO (MainThread) [custom_components.hacs] Stage changed: startup
2024-01-10 15:33:26.835 DEBUG (MainThread) [custom_components.hacs] There are 7 scheduled recurring tasks
2024-01-10 15:33:26.835 INFO (MainThread) [custom_components.hacs] Loading removed repositories
2024-01-10 15:33:27.167 INFO (MainThread) [custom_components.hacs] Loading known repositories
2024-01-10 15:33:29.227 INFO (MainThread) [custom_components.hacs] Starting recurring background task for downloaded repositories
2024-01-10 15:33:29.227 DEBUG (MainThread) [custom_components.hacs] Recurring background task for downloaded repositories done
2024-01-10 15:33:29.227 INFO (MainThread) [custom_components.hacs] Stage changed: running
2024-01-10 15:33:29.441 DEBUG (MainThread) [custom_components.hacs] <QueueManager> The queue is empty
2024-01-10 15:33:29.442 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.critical'. Content did not change
2024-01-10 15:33:29.602 DEBUG (MainThread) [custom_components.hacs] Can update 384 repositories, items in queue 19
2024-01-10 15:33:29.603 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Checking out tasks to execute
2024-01-10 15:33:29.603 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Starting queue execution for 19 tasks
2024-01-10 15:33:29.603 DEBUG (MainThread) [custom_components.hacs] <Integration dolezsa/thermal_comfort> Getting repository information
2024-01-10 15:33:29.605 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Getting repository information
2024-01-10 15:33:29.605 DEBUG (MainThread) [custom_components.hacs] <Plugin nielsfaber/scheduler-card> Getting repository information
2024-01-10 15:33:29.606 DEBUG (MainThread) [custom_components.hacs] <Integration CJNE/ha-myenergi> Getting repository information
2024-01-10 15:33:29.606 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/alexa_media_player> Getting repository information
2024-01-10 15:33:29.606 DEBUG (MainThread) [custom_components.hacs] <Integration amosyuen/ha-epson-projector-link> Getting repository information
2024-01-10 15:33:29.607 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/button-card> Getting repository information
2024-01-10 15:33:29.607 DEBUG (MainThread) [custom_components.hacs] <Integration nielsfaber/scheduler-component> Getting repository information
2024-01-10 15:33:29.607 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Getting repository information
2024-01-10 15:33:29.607 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Getting repository information
2024-01-10 15:33:30.168 DEBUG (MainThread) [custom_components.hacs] <Integration amosyuen/ha-epson-projector-link> Running checks against v1.0.0
2024-01-10 15:33:30.357 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Running checks against 0.0.17
2024-01-10 15:33:30.360 DEBUG (MainThread) [custom_components.hacs] <Integration CJNE/ha-myenergi> Running checks against 0.0.24
2024-01-10 15:33:30.385 DEBUG (MainThread) [custom_components.hacs] <Plugin nielsfaber/scheduler-card> Running checks against v3.2.12
2024-01-10 15:33:30.414 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Running checks against v2.18.2
2024-01-10 15:33:30.419 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/alexa_media_player> Running checks against v4.9.0
2024-01-10 15:33:30.427 DEBUG (MainThread) [custom_components.hacs] <Integration dolezsa/thermal_comfort> Running checks against 2.2.2
2024-01-10 15:33:30.455 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running checks against v3.19.6
2024-01-10 15:33:30.511 DEBUG (MainThread) [custom_components.hacs] <Integration nielsfaber/scheduler-component> Running checks against v3.2.15
2024-01-10 15:33:30.567 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/button-card> Running checks against v4.1.1
2024-01-10 15:33:31.067 DEBUG (MainThread) [custom_components.hacs] Encountered unknown tag 'endif'.
2024-01-10 15:33:31.068 DEBUG (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> Getting repository information
2024-01-10 15:33:31.169 DEBUG (MainThread) [custom_components.hacs] <Integration BottlecapDave/HomeAssistant-OctopusEnergy> Getting repository information
2024-01-10 15:33:31.176 DEBUG (MainThread) [custom_components.hacs] 'state_attr' is undefined
2024-01-10 15:33:31.181 DEBUG (MainThread) [custom_components.hacs] <Integration jaruba/ha-samsungtv-tizen> Getting repository information
2024-01-10 15:33:31.235 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/config-template-card> Getting repository information
2024-01-10 15:33:31.241 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Getting repository information
2024-01-10 15:33:31.266 DEBUG (MainThread) [custom_components.hacs] <Plugin alexarch21/history-explorer-card> Getting repository information
2024-01-10 15:33:31.285 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2024-01-10 15:33:31.397 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Getting repository information
2024-01-10 15:33:31.440 DEBUG (MainThread) [custom_components.hacs] <Integration Alexwijn/SAT> Getting repository information
2024-01-10 15:33:31.973 DEBUG (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> Running checks against v4.0.14
2024-01-10 15:33:31.975 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/config-template-card> Running checks against 1.3.6
2024-01-10 15:33:32.006 DEBUG (MainThread) [custom_components.hacs] <Integration BottlecapDave/HomeAssistant-OctopusEnergy> Running checks against v10.0.2
2024-01-10 15:33:32.055 DEBUG (MainThread) [custom_components.hacs] <Integration Alexwijn/SAT> Running checks against 3.0.1
2024-01-10 15:33:32.081 DEBUG (MainThread) [custom_components.hacs] <Integration jaruba/ha-samsungtv-tizen> Running checks against v1.6.1
2024-01-10 15:33:32.150 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Running checks against v2.5.0
2024-01-10 15:33:32.179 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Running checks against v3.5.1
2024-01-10 15:33:32.252 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.33.0
2024-01-10 15:33:32.349 DEBUG (MainThread) [custom_components.hacs] <Plugin alexarch21/history-explorer-card> Running checks against v1.0.51
2024-01-10 15:33:33.303 DEBUG (MainThread) [custom_components.hacs] 'state_attr' is undefined
2024-01-10 15:33:34.419 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Queue execution finished for 19 tasks finished in 4.82 seconds
2024-01-10 15:33:34.419 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-01-10 15:36:32.737 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Getting repository information
2024-01-10 15:36:33.714 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running checks against v3.19.6
2024-01-10 15:36:38.292 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Getting repository information
2024-01-10 15:36:39.140 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running checks against v3.19.6
2024-01-10 15:36:40.103 INFO (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running pre installation steps
2024-01-10 15:36:40.103 INFO (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Pre installation steps completed
2024-01-10 15:36:40.103 INFO (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running installation steps
2024-01-10 15:36:40.103 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Getting repository information
2024-01-10 15:36:41.039 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running checks against v3.19.6
2024-01-10 15:36:42.138 DEBUG (SyncWorker_8) [custom_components.hacs] Backup for /config/custom_components/tesla_custom, created in /tmp/hacs_backup/tesla_custom
2024-01-10 15:36:42.139 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Local path is set to /config/custom_components/tesla_custom
2024-01-10 15:36:42.139 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Remote path is set to custom_components/tesla_custom
2024-01-10 15:36:42.139 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> ref: v3.19.6 --- tag: v3.19.6
2024-01-10 15:36:42.139 ERROR (MainThread) [custom_components.hacs] <Integration alandtse/tesla> No assets found for release 'tags/v3.19.6'
2024-01-10 15:36:42.151 DEBUG (SyncWorker_9) [custom_components.hacs] Restored /config/custom_components/tesla_custom, from backup /tmp/hacs_backup/tesla_custom
2024-01-10 15:36:42.152 DEBUG (SyncWorker_5) [custom_components.hacs] Backup dir /tmp/hacs_backup/ cleared
2024-01-10 15:36:42.152 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140194249235648] Error handling message: Unknown error (unknown_error) Mark from xxx,xxx.xxx.xxx (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
await repository.async_install()
File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
await self.async_install_repository()
File "/config/custom_components/hacs/repositories/base.py", line 995, in async_install_repository
raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details`

**Comment by alandtse** [comment]
Sorry, I meant the hacs ticket.

**Comment by mcc05** [comment]
My bad, done :)

**Comment by mcc05** [comment]
So I did have show beta releases on, but I would have expected "pre-release" to mean before beta-release, but that may not be the case :)

**Comment by alandtse** [comment]
Ok thanks. Didn't realize you had that turned on. Guess it's working as expected. I'll fix that release in a few weeks but you're not missing anything. it just suppresses some warnings. You can get it by just downloading the dev branch anyway.
