### ISSUE TITLE
Error when trying to wake up vehicle by starting charging

### ISSUE THREAD

**Issue by tobbensoft** [alandtse/tesla#82]
## Version of the custom_component

Release V1.3.0

## Configuration

N/A

## Describe the bug

When starting charging for a sleeping vehicle I get the below error.

Working fine when it's awake.

## Debug log

```2021-10-21 10:34:12 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 5 days, 7:28:33
2021-10-21 10:34:12 DEBUG (MainThread) [teslajsonpy.connection] post: https://owner-api.teslamotors.com/api/1/vehicles/5025388345911957/command/charge_start {}
2021-10-21 10:34:12 DEBUG (MainThread) [teslajsonpy.connection] 408: {"response":null,"error":"vehicle unavailable: {:error=>\"vehicle unavailable:\"}","error_description":""}
2021-10-21 10:34:12 DEBUG (MainThread) [teslajsonpy.controller] Exception: vehicle_unavailable
api(('START_CHARGE',) {'path_vars': {'vehicle_id': 5025388345911957}, 'wake_if_asleep': True})
2021-10-21 10:34:12 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139941383171328] vehicle_unavailable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/config/custom_components/tesla_custom/tesla_device.py", line 35, in wrapped
    result = await func(*args, **kwargs)
  File "/config/custom_components/tesla_custom/switch.py", line 35, in async_turn_on
    await self.tesla_device.start_charge()
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/homeassistant/charger.py", line 65, in start_charge
    data = await self._controller.api(
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 166, in wake_up
    result = await wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/controller.py", line 1189, in api
    return await self.__connection.post(
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 167, in post
    return await self.__open(
  File "/usr/local/lib/python3.9/site-packages/teslajsonpy/connection.py", line 217, in __open
    raise TeslaException(resp.status_code, "vehicle_unavailable")
teslajsonpy.exceptions.TeslaException: vehicle_unavailable



```

**Comment by alandtse** [comment]
Looks like Tesla has changed the functionality so it return vehicle_unavailable when vehicles are sleeping.

You should do a wake_up command before the charge command as a workaround.
