### ISSUE TITLE
Unknown endpoint name SHARE

### ISSUE THREAD

**Issue by Nessy1970** [alandtse/tesla#862]
## Version of the custom_component

3.19.8

## Configuration

```
Core 2024.2.2
Supervisor 2024.01.1
Operating System 11.5
Interface utilisateur 20240207.1

Script :
envoie_la_position_de_fernanda_dans_la_voiture:
  alias: Envoie la position de fernanda dans la voiture
  sequence:
    - service: tesla_custom.api
      data:
        command: SHARE
        parameters:
          path_vars:
            vehicle_id: "{{ state_attr('binary_sensor.la_fleche_bleue_online', 'id') }}" # see the "Getting your Vehicle ID" section 
          type: "share_ext_content_raw"
          locale: "fr-fr"
          value:
            android.intent.extra.TEXT: "{{ states('sensor.gsm_fernanda_ha_app_lieu_geocode') }}" # Address goes here
          timestamp_ms: >-
            {{ as_timestamp(now()) | int }}
```

## Describe the bug

I had been using this feature for over 1 year, a few months ago (around October 2023) it no longer worked following an update to this repo. I was waiting to see if it would be reactivated in an update, but still nothing today. Or the way of calling to change, but in the wiki it's always the same procedure.

## Debug log

```text

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1269, in api
    endpoint = self.endpoints[name]
               ~~~~~~~~~~~~~~^^^^^^
KeyError: 'SHARE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 600, in _async_run
    return await self.script.async_run(script_vars, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1600, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 435, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 487, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 512, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 485, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 723, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/services.py", line 56, in async_call_tesla_service
    response = await api(service_call)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/services.py", line 116, in api
    response = await controller.api(name=command, path_vars=path_vars, **parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1271, in api
    raise ValueError("Unknown endpoint name " + name) from ex
ValueError: Unknown endpoint name SHARE

```

**Comment by Nessy1970** [comment]
> According to https://github.com/zabuldon/teslajsonpy/blob/master/teslajsonpy/endpoints.json and looking at the diff `SHARE` command became `SEND_TO_VEHICLE`

Indeed, you have to replace "SHARE" with "SEND_TO_VEHICLE" and everything works correctly again.
THANKS

**Comment by skipishere** [comment]
No worries, glad to have helped
