### ISSUE TITLE
Battery status not available after last update

### ISSUE THREAD

**Issue by Assiolo** [alandtse/tesla#880]
after the last update the integration no longer calls the battery status "This entity is no longer provided by the tesla_custom integration. If the entity is no longer used, delete it in settings." happened to anyone else?

**Comment by Zappo-II** [comment]
Looks like it explodes in general trying to initiate it's sensors...
```
2024-03-05 16:21:12.395 ERROR (MainThread) [homeassistant.components.sensor] tesla_custom: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 599, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1259, in async_device_update
await self.async_update()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 530, in async_update
await self.coordinator.async_request_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 263, in async_request_refresh
await self._debounced_refresh.async_call()
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
await task
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 289, in async_refresh
await self._async_refresh(log_failures=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 549, in state
value = self.native_value
^^^^^^^^^^^^^^^^^
File "/config/custom_components/tesla_custom/sensor.py", line 191, in native_value
return float(self._car.charger_power)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by skipishere** [comment]
> float(self._car.charger_power)

Given that line was added in the last version that does seem like the root cause

**Comment by Zappo-II** [comment]
Was changed in this commit:
https://github.com/alandtse/tesla/commit/e97c15f2b3865cdead0021660d050b619a9aac1f

**Comment by Zappo-II** [comment]
...which is part of the 3.19.10 release.

**Comment by FileGo** [comment]
Same here, downgrade to v3.19.9 resolved the issue.

**Comment by e2m32** [comment]
Adding a +1 here
