### ISSUE TITLE
ValueError: Unknown endpoint name SHARE - when trying to Share

### ISSUE THREAD

**Issue by nreilly** [alandtse/tesla#893]
## Version of the custom_component
3.20.1

## Configuration
Car: 2024.2.7 d522c44937f7

## Describe the bug

Attempting to follow https://github.com/alandtse/tesla/wiki/Share

It appears the command needs to be changed to be "SEND_TO_VEHICLE" instead of "SHARE" per https://github.com/zabuldon/teslajsonpy/blob/dev/teslajsonpy/endpoints.json

## Debug log

```
[547372202304] Error handling message: Unknown error (unknown_error) Nathan from 10.16.2.88 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1326, in api
    endpoint = self.endpoints[name]
               ~~~~~~~~~~~~~~^^^^^^
KeyError: 'SHARE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 795, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1600, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 435, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 487, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 512, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 485, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 723, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/services.py", line 56, in async_call_tesla_service
    response = await api(service_call)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/services.py", line 116, in api
    response = await controller.api(name=command, path_vars=path_vars, **parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1328, in api
    raise ValueError("Unknown endpoint name " + name) from ex
ValueError: Unknown endpoint name SHARE
```

**Comment by alandtse** [comment]
Go ahead and update the wiki. This doesn't require any code change.s

**Comment by nreilly** [comment]
Updated
