### ISSUE TITLE
Powerwall Issue:  HA log shows constant entries for TypeErrors

### ISSUE THREAD

**Issue by Steve-gnome** [alandtse/tesla#938]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### Version of the Tesla component

v3.20.5

### Version of the Powerwall Gateway software

23.36.3

### Model

2

### Current Behavior

error logs flooded with the same message about every minute

### Expected Behavior

I dont expect to see any errors

### Debug logs

```true
TypeError: type NoneType doesn't define __round__ method
2024-04-06 15:28:19.854 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in __async_calculate_state
state = self._stringify_state(available)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in _stringify_state
if (state := self.state) is None:
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 548, in state
value = self.native_value
^^^^^^^^^^^^^^^^^
File "/config/custom_components/tesla_custom/sensor.py", line 443, in native_value
return round(self._energysite.energy_left)
```

**Comment by Steve-gnome** [comment]
a - think i found a duplicate of this with better searching -
