### ISSUE TITLE
Polling not possible

### ISSUE THREAD

**Issue by paky79** [alandtse/tesla#962]
### Is there an existing issue for this?

- [X] I have searched both the existing open issues & recently closed issues and did not find a duplicate of this issue.

### I have read about the Fleet API and understand I may need to use it

- [X] I understand issues relating to read only commands will be auto closed if not using the Fleet API.

### Version of the Tesla component

3.21.0

### Version of the Tesla car software

2024.8.9

### Model

Model Y

### Current Behavior

I saw hundreds of warnings in the main log like this:Unable to get vehicle data during poll. 429: TOO_MANY_REQUESTS. After that the polling was disable and it is impossible to enable again. Not possible to receive any data or to send any command. It seems completely shutted-off

### Expected Behavior

Polling available

### Debug logs

```true
2024-05-09 19:24:40.347 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-05-09 19:24:40.348 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 45 Interval 60
2024-05-09 19:24:40.348 DEBUG (MainThread) [teslajsonpy.controller] 75763: online. Polling policy: normal. Update state: trying_to_sleep. Since last park: 9648. Since last wake up: 9647. Idle interval: 600. shift_state: None sentry: None climate: None, charging: None 
2024-05-09 19:24:40.348 DEBUG (MainThread) [teslajsonpy.controller] 75763: online; Polling policy set to 'normal', trying to sleep; scan throttled to 660 seconds and will ignore updates for -1715274820 seconds
2024-05-09 19:24:40.348 DEBUG (MainThread) [teslajsonpy.controller] 75763: Updating VEHICLE_DATA
2024-05-09 19:24:40.349 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:41:21
2024-05-09 19:24:40.350 DEBUG (MainThread) [teslajsonpy.connection] get: https://c03d64a7-tesla-http-proxy/api/1/vehicles/XP7YGCEK0RB275763/vehicle_data?endpoints=charge_state%3Bclimate_state%3Bdrive_state%3Bgui_settings%3Bvehicle_config%3Bvehicle_state%3Blocation_data {}
2024-05-09 19:24:40.415 DEBUG (MainThread) [teslajsonpy.connection] 429: Retry later

2024-05-09 19:24:40.415 WARNING (MainThread) [teslajsonpy.controller] Unable to get vehicle data during poll. 429: TOO_MANY_REQUESTS
2024-05-09 19:24:40.416 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.069 seconds (success: True)
2024-05-09 19:24:40.528 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:41:21
2024-05-09 19:24:40.529 DEBUG (MainThread) [teslajsonpy.connection] post: https://c03d64a7-tesla-http-proxy/api/1/vehicles/XP7YGCEK0RB275763/command/charge_start {}
2024-05-09 19:24:45.204 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-05-09 19:24:45.204 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 50 Interval 60
2024-05-09 19:24:45.205 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.001 seconds (success: True)
2024-05-09 19:24:47.968 DEBUG (MainThread) [teslajsonpy.connection] 500: {"response":null,"error":"context deadline exceeded","error_description":""}

2024-05-09 19:24:47.969 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140005009783488] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 144, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tesla_custom/switch.py", line 114, in async_turn_on
    await self._car.start_charge()
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 1113, in start_charge
    data = await self._send_command("START_CHARGE")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 775, in _send_command
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 760, in _send_command
    data = await self._controller.api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1367, in api
    response = await self.__post_with_retries(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1390, in __post_with_retries
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 218, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
2024-05-09 19:24:50.346 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-05-09 19:24:50.347 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 55 Interval 60
2024-05-09 19:24:50.347 DEBUG (MainThread) [teslajsonpy.controller] 75763: online. Polling policy: normal. Update state: trying_to_sleep. Since last park: 9658. Since last wake up: 9657. Idle interval: 600. shift_state: None sentry: None climate: None, charging: None 
2024-05-09 19:24:50.347 DEBUG (MainThread) [teslajsonpy.controller] 75763: online; Polling policy set to 'normal', trying to sleep; scan throttled to 660 seconds and will ignore updates for -1715274830 seconds
2024-05-09 19:24:50.347 DEBUG (MainThread) [teslajsonpy.controller] 75763: Updating VEHICLE_DATA
2024-05-09 19:24:50.348 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:41:11
2024-05-09 19:24:50.349 DEBUG (MainThread) [teslajsonpy.connection] get: https://c03d64a7-tesla-http-proxy/api/1/vehicles/XP7YGCEK0RB275763/vehicle_data?endpoints=charge_state%3Bclimate_state%3Bdrive_state%3Bgui_settings%3Bvehicle_config%3Bvehicle_state%3Blocation_data {}
2024-05-09 19:24:50.412 DEBUG (MainThread) [teslajsonpy.connection] 429: Retry later

2024-05-09 19:24:50.413 WARNING (MainThread) [teslajsonpy.controller] Unable to get vehicle data during poll. 429: TOO_MANY_REQUESTS
2024-05-09 19:24:50.414 DEBUG (MainThread) [custom_components.tesla_custom] Finished fetching tesla_custom data in 0.068 seconds (success: True)
2024-05-09 19:24:50.542 DEBUG (MainThread) [teslajsonpy.connection] 500: {"response":null,"error":"context deadline exceeded","error_description":""}

2024-05-09 19:24:50.543 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140005009783488] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tesla_custom/switch.py", line 114, in async_turn_on
    await self._car.start_charge()
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 1113, in start_charge
    data = await self._send_command("START_CHARGE")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 775, in _send_command
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 760, in _send_command
    data = await self._controller.api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1367, in api
    response = await self.__post_with_retries(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1390, in __post_with_retries
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 218, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException
2024-05-09 19:24:55.203 DEBUG (MainThread) [custom_components.tesla_custom] Running controller.update()
2024-05-09 19:24:55.204 DEBUG (MainThread) [teslajsonpy.controller] Get vehicles. Force: False Time: 60 Interval 60
2024-05-09 19:24:55.204 DEBUG (MainThread) [teslajsonpy.connection] Token expiration in 0:41:06
```

**Comment by paky79** [comment]
Update: I saw an error in the main log related websocket_api:

homeassistant.components.websocket_api.http.connection
components/websocket_api/commands.py:239
Integrazione: Home Assistant WebSocket API (documentazione, problemi)
Prima occorrenza: 19:54:45 (11 occorrenze)
Ultima registrazione: 21:27:28

[139822363357632] Unexpected exception
[139822131757888] Unexpected exception
[139822113500864] Unexpected exception
[139822131729088] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 144, in async_handle_turn_service
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tesla_custom/switch.py", line 114, in async_turn_on
    await self._car.start_charge()
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 1113, in start_charge
    data = await self._send_command("START_CHARGE")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 775, in _send_command
    raise ex
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/car.py", line 760, in _send_command
    data = await self._controller.api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1367, in api
    response = await self.__post_with_retries(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1390, in __post_with_retries
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 218, in __open
    raise TeslaException(resp.status_code)
teslajsonpy.exceptions.TeslaException

**Comment by peter-funktionIT** [comment]
I have the same issue.
Also running 3.21.0
Lots of log in tesla_http_proxy (https://github.com/iainbullock/tesla-http-proxy-docker/issues) with this
`tesla_http_proxy  | 2024-05-09T19:26:28Z [debug] Server returned 429: Too Many Requests: Retry later`

**Comment by rileymd88** [comment]
Same issue here: https://github.com/alandtse/tesla/issues/961#issuecomment-2103298916

**Comment by alandtse** [comment]
Closing since this is a dupe. I'll rename #961; please follow that.
